#!/bin/bash
# .openshift/action_hooks/deploy

# Composer
unset GIT_DIR
cd $OPENSHIFT_REPO_DIR
/opt/rh/php54/root/usr/bin/php composer.phar install --no-dev --no-interaction

# Generate proxies
vendor/bin/doctrine-module orm:generate-proxies
#symlink to documents
ln -s $OPENSHIFT_DATA_DIR public/documents

# temp solution for overriding arraycollection in doctrine before they fix the sort bug
rm vendor/doctrine/collections/lib/Doctrine/Common/Collections/ArrayCollection.php
cp $OPENSHIFT_DATA_DIR/ArrayCollection.php vendor/doctrine/collections/lib/Doctrine/Common/Collections/ArrayCollection.php
# end temp sol
