<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Fund\Module'                        => __DIR__ . '/Module.php',
    'Fund\Controller\FundController'     => __DIR__ . '/src/Fund/Controller/FundController.php',
    'FundTest\Framework\TestCase'        => __DIR__ . '/tests/Fund/Framework/TestCase.php',
    'FundTest\SampleTest'                => __DIR__ . '/tests/Fund/SampleTest.php',
);
