

<div class="container">
  <div class="page-header">
    <h1>Om fondout</h1>
    <p class="lead">
      Fondout är en internettjänst där vi granskar hur fonderna (alltså dina sparpengar) jobbar med hållbarhet, för det tycker vi är viktigt.</p>
    <p>
      Hållberhet betyder olika för alla. Kanske handlar det om oljebolag (CO2), barnarbete, miljöförstöring eller djurförsök, vad tycker du är viktigt? Det ska vara enkelt att jämföra fonder. Vi vill att alla ska kunna förstå själva vad de väljer. Det behövs fler mätvärden än avgifter och avkastning för att kunna spara hållbart.
      Vi kan inte göra detta själva. Men, med hjälp och samarbete från eldsjälar, intresseorganisationer, banker, forskare, pensionsbolag och från dig kan vi föra mer hållbara fondval för en grön ekonomi och en bättre värld.
    </p>
  </div>



  <section class="row">
    <div class="col-md-6" >

      <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('contact', array('action' => 'submit')));
        $form->prepare();

        echo $this->form()->openTag($form);
        /*echo $this->formHidden($form->get('id'));
        echo $this->formRow($form->get('name'));
        echo $this->formRow($form->get('email'));
        echo $this->formSubmit($form->get('submit'));*/
        echo $this->formCollection($form);
        echo $this->form()->closeTag();

        ?>

<!--
      <form action="#" role="form" id="contact">
        <div class="form-group">
          <label for="name">Namn <span class="required">*</span></label>
          <input type="text" name="name" class="form-control" id="name" required>
        </div>
        <div class="form-group">
          <label for="email">E-post address <span class="required">*</span></label>
          <input type="email" name="email" class="form-control" id="email" data-parsley-email required>
        </div>
        <div class="form-group">
          <label for="subject">Ämne <span class="required">*</span></label>
          <input type="text" name="subject" class="form-control" id="subject" required>
        </div>
        <div class="form-group">
          <label for="message">Meddelande</label>
          <textarea name="message" rows="5" class="form-control" id="message"></textarea>
        </div>
        <button type="submit" name="submit" class="btn btn-primary">Skicka</button>
      </form>
    -->
    </div>
    <div class="row">
      <address class="vcard">
        <strong><a class="url fn org" href="http://www.fondout.dev">Fondout</a></strong><br />
        <a class="email" href="mailto:info@fondout.dev">info@fondout.dev</a><br />
        <div class="adr">
          <div class="street-address">Scheelevägen 15</div>
          <span class="postal-code">223 70</span>,
          <span class="locality">Lund</span>,
          <span class="region">Skåne</span>,
          <span class="country-name">Sverige</span>
        </div>
        <span class="tel">0701470701</span>
      </address>

      <div class="col-md-6">
        <div class="row">
          <div class="thumbnail col-md-4">
            <img src='/img/people/stefan.png' alt="Stefan Carlsson" class="img-thumbnail">
            <div class="caption">
              <h4>Stefan Carlsson</h4>
            </div>
          </div>
          <div class="thumbnail col-md-4">
          <img src='/img/people/petter.png' alt="Petter Söderlund" class="img-thumbnail">
            <div class="caption">
              <h4>Petter Söderlund</h4>
            </div>
          </div>
          <div class="thumbnail col-md-4">
          <img src='/img/people/marcus.jpg' alt="Marcus Lindfeldt" class="img-thumbnail">
            <div class="caption">
              <h4>Marcus Lindfeldt</h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div><!-- /.container -->
