

<div class="container">
  <div class="page-header">
    <h1>Om fondout</h1>
    <p class="lead">
      Fondout är en internettjänst där vi granskar hur fonderna (alltså dina sparpengar) jobbar med hållbarhet, för det tycker vi är viktigt.</p>
      <p>
        Hållberhet betyder olika för alla. Kanske handlar det om oljebolag (CO2), barnarbete, miljöförstöring eller djurförsök, vad tycker du är viktigt? Det ska vara enkelt att jämföra fonder. Vi vill att alla ska kunna förstå själva vad de väljer. Det behövs fler mätvärden än avgifter och avkastning för att kunna spara hållbart.
        Vi kan inte göra detta själva. Men, med hjälp och samarbete från eldsjälar, intresseorganisationer, banker, forskare, pensionsbolag och från dig kan vi föra mer hållbara fondval för en grön ekonomi och en bättre värld.
      </p>
    </div>



    <div class="row">
      <div class="col-md-6" >

        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('contact', array('action' => 'submit')));
        $form->prepare();
        echo $this->form()->openTag($form)
        ?>
        <?php foreach ($form as $element) : ?>
          <div class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
            <?php
            if ('submit' != $element->getAttribute('type')) { ?>
            <label class="control-label"><?php echo $element->getLabel() ?></label>
            <?php
            $element->setAttribute('class', 'form-control')
            ->setAttribute('placeholder', $element->getLabel());
          } else {
            $element->setAttribute('class', 'btn btn-success');
          }
          echo $this->formElement($element);
          if ($this->formElementErrors($element)) : ?>
          <?php
          echo $this->formElementErrors()
          ->setMessageOpenFormat('<p class="help-block">')
          ->setMessageSeparatorString('</p><p class="help-block">')
          ->setMessageCloseString('</p>')
          ->render($element);
          ?>
        <?php endif; ?>
      </div>

      <?php
      endforeach;
      echo $this->form()->closeTag() ?>

    </div>
    <div class="col-md-6" >
      <div class="row">
        <address class="vcard col-md-12">
          <strong><a class="url fn org" href="http://www.fondout.dev">Fondout</a></strong><br />
          <a class="email" href="mailto:info@fondout.dev">info@fondout.dev</a><br />
          <div class="adr">
            <div class="street-address">Scheelevägen 15</div>
            <span class="postal-code">223 70</span>,
            <span class="locality">Lund</span>,
            <span class="region">Skåne</span>,
            <span class="country-name">Sverige</span>
          </div>
          <span class="tel">0701470701</span>
        </address>
      </div>
      <div class="row">

        <div class="col-md-4">
          <div class="thumbnail">
            <img src='/img/people/stefan.png' alt="Stefan Carlsson">
            <div class="caption">
              <h4>Stefan Carlsson</h4>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="thumbnail">
            <img src='/img/people/petter.png' alt="Petter Söderlund">
            <div class="caption">
              <h4>Petter Söderlund</h4>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="thumbnail">
            <img src='/img/people/marcus.jpg' alt="Marcus Lindfeldt">
            <div class="caption">
              <h4>Marcus Lindfeldt</h4>
            </div>
          </div>
        </div>
      </div>
      </div>
  </div>
</div><!-- /.container -->
