<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Sparfabriken'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath() . '/css/style.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/vendor/bootstrap/dist/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/vendor/jquery/dist/jquery.min.js')
            ->prependFile($this->basePath() . '/vendor/respond/dest/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/vendor/dist/html5shiv.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <header class="navbar navbar-inverse navbar-static-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand fondout-logo" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Sparfabriken') ?></a>
                </div>
                <nav class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Hem') ?></a></li>
                        <li><a href="<?php echo $this->url('funds') ?>"><?php echo $this->translate('Fondsök') ?></a></li>
                        <li><a href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('Om oss') ?></a></li>
                    </ul>
                </nav><!--/.nav-collapse -->
            </div>
        </header>
            <?php echo $this->content; ?>
            <footer>
                <div class="container">
                    <a class="fondout-logo" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Sparfabriken') ?></a>
                    <p><?php echo $this->translate('Jämför dina fonder på nätet.') ?></p>
                    <ul class="footer-links">
                        <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Hem') ?></a></li>
                        <li>&bull;</li>
                        <li><a href="<?php echo $this->url('funds') ?>"><?php echo $this->translate('Fondsök') ?></a></li>
                        <li>&bull;</li>
                        <li><a href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('Om oss') ?></a></li>
                    </ul>
                    <p class="copyright">&copy; 2012 - <?php echo date('Y') ?> <a href="/">sparfabriken.se</a>.</p>
                </div>
            </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
