<?php echo $this->doctype(); ?>
<html lang="en">
      <?php
        $this->headMeta()->setCharset('utf-8');
        $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        $this->headMeta()->appendName(
        'description',
        $this->translate('Har du koll på hur dina fonder investerar? Sparahållbart.se ger en inblick i vilka fonder som investerar i fossila bränslen, förbjudna vapen, alkohol, tobak och spelbolag.')
        );
      ?>

      <?php echo $this->headMeta();?>

        <link rel="icon"
              type="image/ico"
              href="/img/favicon.ico" />

        <meta property="og:image" content="/img/sparahallbart-round.png" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Hitta hållbara fonder på sparahållbart.se" />

        <?php echo $this->headTitle($this->translate('Sparahållbart.se'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Le styles -->
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath() . '/css/style.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/vendor/bootstrap/dist/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/vendor/jquery/jquery.min.js')
            ->prependFile($this->basePath() . '/vendor/respond/dest/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/vendor/dist/html5shiv.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath() . '/vendor/jquery-cookie/jquery.cookie.js')
        ; ?>
    </head>
    <body>
      <!-- Google Tag Manager -->
      <noscript>
        <iframe src="//www.googletagmanager.com/ns.html?id=GTM-5F39B2" height="0" width="0" style="display:none;visibility:hidden">
        </iframe>
      </noscript>
      <script>
        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-5F39B2');
      </script>
      <!-- End Google Tag Manager -->
      <!-- Facebook -->
      <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/sv_SE/sdk.js#xfbml=1&version=v2.3";
            fjs.parentNode.insertBefore(js, fjs);
          }(document, 'script', 'facebook-jssdk'));</script>
      <!-- End Facebook -->

        <header class="navbar">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="/img/sparahallbart.png" alt='<?php echo $this->translate('Sparahållbart') ?>'></a>
                </div>
                <nav class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Hem') ?></a></li>
                        <li><a href="<?php echo $this->url('funds') ?>"><?php echo $this->translate('Fondsök') ?></a></li>
                        <li><a href="/fundcompany/apfonderna"><?php echo $this->translate('Ap-Fonderna') ?></a></li>
                        <li><a href="<?php echo $this->url('qa') ?>"><?php echo $this->translate('Om Sparahållbart') ?></a></li>
                    </ul>
                </nav><!--/.nav-collapse -->
            </div>
        </header>
            <?php echo $this->content; ?>
            <footer>
                <div class="container">
                    <div class="row">
                      <div class="fb-box col-sm-6 col-md-4 col-md-push-4  hidden-xs col-sm-push-6">
                        <h4>Facebook</h4>
                        <div class="fb-page" data-href="https://www.facebook.com/sparahallbart" data-width="500" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/sparahallbart"><a href="https://www.facebook.com/sparahallbart">Spara hållbart</a></blockquote></div></div>
                      </div>

                      <div class=" hidden-xs hidden-sm col-md-4 col-md-push-4">
                        <h4>Nyhetsbrev</h4>
                        <!-- Begin MailChimp Signup Form -->
                        <div id="mc_embed_signup">
                        <form action="//fondout.us8.list-manage.com/subscribe/post?u=0767fce748f978490a18638d8&amp;id=e5626c650c" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                            <div id="mc_embed_signup_scroll">
                              <p>Prenumerera på vårt nyhetsbrev och få uppdateringar om hållbart sparande.</p>
                        <div class="mc-field-group">
                        	<label for="mce-EMAIL">Email </label>
                        	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
                        </div>
                        	<div id="mce-responses" class="clear">
                        		<div class="response" id="mce-error-response" style="display:none"></div>
                        		<div class="response" id="mce-success-response" style="display:none"></div>
                        	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                            <div style="position: absolute; left: -5000px;"><input type="text" name="b_0767fce748f978490a18638d8_e5626c650c" tabindex="-1" value=""></div>
                            <div class="clear"><input type="submit" value="Följ oss" name="subscribe" id="mc-embedded-subscribe" class="button btn btn-primary btn-md"></div>
                            </div>
                        </form>
                        </div>
                        <!--End mc_embed_signup-->
                      </div>

                      <div class="col-sm-6 col-md-4 col-md-pull-8 col-sm-pull-6">
                        <h4 class="">Om oss</h4>
                        <p class="">Sparahållbart.se - Fondjämförelser ur ett hållbarhetsperspektiv har aldrig varit enklare drivs av Sparfabriken AB. För frågor om tjänsten eller för samarbeten kontakta oss på &#104;&#101;&#106;&#064;&#115;&#112;&#097;&#114;&#102;&#097;&#098;&#114;&#105;&#107;&#101;&#110;&#046;&#115;&#101;</p>
                        <a href="http://www.sparfabriken.se"><img class="" src="/img/sparfabriken.png" alt="Sparfabriken logo"></a>
                        <p class="copyright">Sparfabriken AB - Lund, Sverige. Org. nr. 556997-2374.<br><a href="http://www.sparfabriken.se">www.sparfabriken.se</a><br><br>&copy; <!--2012 --> <?php echo date('Y') ?> <a href="/">sparahallbart.se</a></p>
                      </div>
                    </div>
                </div>
            </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
