<?php echo $this->doctype(); ?>
<html lang="sv">
      <?php
        $this->headMeta()
            //->setCharset('utf-8')
            //->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0');

        $this->headMeta()->appendName(
          'description',
          $this->translate('Spara hållbart är ett SRI-screeningsverkyg för aktiefonder. Med vårt verktyg kan du genomlysa fonder på branscher som vapen och fossila bränslen.')
        );
      ?>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">

      <?php echo $this->headMeta();?>


        <link rel="icon"
              type="image/ico"
              href="/img/favicon.ico" />

        <meta property="og:image" content="/img/sparahallbart-round.png" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Hitta hållbara fonder på sparahållbart.se" />

        <?php echo $this->headTitle($this->translate('Sparahållbart.se'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Le styles -->
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath() . '/css/style.css') ?>
    </head>
    <body>
      <!-- Google Tag Manager -->
      <noscript>
        <iframe src="//www.googletagmanager.com/ns.html?id=GTM-5F39B2" height="0" width="0" style="display:none;visibility:hidden">
        </iframe>
      </noscript>
      <script>
        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-5F39B2');
      </script>
      <!-- End Google Tag Manager -->
      <!-- Facebook -->
      <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/sv_SE/sdk.js#xfbml=1&version=v2.3";
            fjs.parentNode.insertBefore(js, fjs);
          }(document, 'script', 'facebook-jssdk'));</script>
      <!-- End Facebook -->

        <header class="navbar">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="/img/sparahallbart.png" alt='<?php echo $this->translate('Sparahållbart') ?>'></a>
                </div>
                <nav class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Hem') ?></a></li>
                        <li><a href="<?php echo $this->url('funds') ?>"><?php echo $this->translate('Fondsök') ?></a></li>
                        <li><a href="/fundcompany/apfonderna"><?php echo $this->translate('AP-Fonderna') ?></a></li>
                        <li><a href="<?php echo $this->url('qa') ?>"><?php echo $this->translate('Om Sparahållbart') ?></a></li>
                    </ul>
                </nav><!--/.nav-collapse -->
            </div>
        </header>
            <?php echo $this->content; ?>
            <footer>
                <div class="container">
                    <div class="row">
                      <div class="col-sm-12 col-md-4">
                        <h4 class="">Om oss</h4>
                        <p class="">Sparahallbart.se drivs på ideella grunder för ett oberoende alternativ för hållbart sparande i fonder. För frågor om tjänsten kontakta oss på &#104;&#101;&#106;&#064;&#115;&#112;&#097;&#114;&#102;&#097;&#098;&#114;&#105;&#107;&#101;&#110;&#046;&#115;&#101;</p>

                        <p class="copyright">
													&copy; <!--2012 --> <?php echo date('Y') ?>
													<a href="/">sparahallbart.se</a></p>
                      </div>
                      <div class="fb-box col-md-8 hidden-sm hidden-xs">
                        <h4>Facebook</h4>
                        <div class="fb-page" data-href="https://www.facebook.com/sparahallbart" data-width="500" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/sparahallbart"><a href="https://www.facebook.com/sparahallbart">Spara hållbart</a></blockquote></div></div>
                      </div>

                      <!--<div class=" hidden-xs  col-sm-6 col-md-4 col-md-push-4 col-sm-push-6">
                        <h4>För fondbolag</h4>
                        <p>Vill ni lista era fonder på sparahållbart.se? Läs mer i våra produktblad. Medlemskap är öppet för alla fondbolag med två medlemsnivåer. Det finns även möjlighet för vidare exponering med displayannonser. </p><a href="/products" class="btn btn-success">Läs mer om medlemskap för fondbolag</a>
                      </div>-->
                    </div>
                </div>
            </footer>
        <?php echo $this->inlineScript() ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/vendor/bootstrap/dist/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/vendor/jquery/jquery.min.js')
            ->prependFile($this->basePath() . '/vendor/respond/dest/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/vendor/dist/html5shiv.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath() . '/vendor/jquery-cookie/jquery.cookie.js')
        ; ?>
    </body>
</html>
