<div class="alternate-funds">
  <?php $i = 1; ?>
  <?php foreach ($funds as $fund): ?>
    <div class="col-md-6 alternate-fund">

        <div class="row well">
          <a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array('id' => $fund->url))) ?>" title="" target="_blank">
          <div class="col-sm-4 col-xs-12">
            <?php echo  ($fund->fundCompany->premium) ? "<img class='fund-logo' src='/img/fund-company/logo/" . $fund->fundCompany->id . ".png' alt='" . $fund->fundCompany->name . " logo'>" : "" ?>
            <h4>
                <?php echo $this->translate($fund->name) ?>
            </h4>
          </div>
          <div class="col-sm-4 col-xs-5">
            <?php echo "<img class='bar' src='/img/bar/bar" . $fund->getMeasureScore('fossil') . ".png' alt='Fossil " . $fund->getMeasureScore('fossil') . "/10'>"    ?>

            <?php echo "<img class='bar' src='/img/bar/bar" . $fund->getMeasureScore('weapon') . ".png' alt='Vapen " . $fund->getMeasureScore('weapon') . "/10'>"    ?>

            <?php echo "<img class='thin-bar' src='/img/thin-bar/thinbar" . $fund->getMeasureScore('alcohol') . ".png' alt='Alkohol " . $fund->getMeasureScore('alcohol') . "/10'>\n" ?>
            <?php echo "<img class='thin-bar' src='/img/thin-bar/thinbar" . $fund->getMeasureScore('tobacco') . ".png' alt='Tobak " . $fund->getMeasureScore('tobacco') . "/10'>\n"?>
            <?php echo "<img class='thin-bar' src='/img/thin-bar/thinbar" . $fund->getMeasureScore('gambling') . ".png' alt='Spel " . $fund->getMeasureScore('gambling') . "/10'>\n"?>
            <br>
            <img class="round-symbol" src="/img/symbols/fossil.png" alt="Fossila bränslen">
            <img class="round-symbol" src="/img/symbols/weapon.png" alt="Vapen">
            <img class="thin-symbol" src="/img/symbols/alcohol.png" alt="Alkohol">
            <img class="thin-symbol" src="/img/symbols/tobacco.png" alt="Tobak">
            <img class="thin-symbol" src="/img/symbols/gambling.png" alt="Spel">
          </div>
          </a>
          <div class="col-sm-4 col-xs-7">
            <a class="fundinfo-btn btn btn-xxs" href="/fundcompany/<?php echo $this->translate($fund->company->url) ?>">
                <?php echo $this->translate($fund->company->name) ?>
            </a>
            <br>
            <a class="fundinfo-btn btn btn-xxs" href="<?php echo $this->escapeHtmlAttr($this->url('funds', array(), array('query' => array('fondoutcategory[]' => $fund->fondoutcategory->id)))); ?>">
              <?php echo $this->translate($fund->fondoutcategory->longName) ?>
            </a>
          </div>
        </div>

    </div>

    <?php if ($i++ == $limit) break; ?>
  <?php endforeach; ?>
</div>
