<?php
$this->headTitle("Pensionssparande", 'PREPEND');
$this->headMeta()->appendName('description', $this->translate('DESCT TEST TEXT '));
?>

<div class="container">
	<div class="section">
		<h1>
		Premiepension
		</h1>

		<p>Sveriges pensionssystem gör att en väldigt stor andel av vår befolkning äger fonder och att de aktivt kan välja dessa. Valet i premiepensionen kan alla göra som genom arbete eller studier har tjänat in pension efter 1995. 2,5% av intjänad lön upp till 7,5 basbelopp sätts av varje år. I det statliga premiepensionssystemet finns idag ca 800 fonder att välja mellan. Flera av dessa hittar du i vårt <a href="<?php echo $this->url('funds') ?>">fondsök</a>. Pensionsmyndigheten har generellt förhandlat fram stora <a target="_blank" href="http://www.pensionsmyndigheten.se/RabattPaFondavgifterna.html">rabatter</a> på de fonder som finns att köpa i jämförelse med vad fonden skulle kosta om du köpte den direkt från fondbolaget. Detta beror på att myndigheten sköter administrationen av kunden och att fondbolaget har möjlighet till att få in stora volymer till låg kostnad om produkten säljer bra.
		<a target="_blank" href="http://www.pensionsmyndigheten.se/DuValjerHurDinaPengarPlaceras.html">För vidare information om pensionsmyndigheten klicka här.</a>
		<p>
			AP-fonderna är ett samlingsnamn för de olika allmänna pensionsfonder som finns i Sverige. Sjunde AP-fonden (AP7) är den AP-fond som flest känner till. Denna fond är det statliga alternativt i premiepensionssystemet (tidigare kallat PPM) och där alla pengar hamnar från de som avstått att göra ett aktivt val av fonder (vilket ca 40% har avstått ifrån). AP7 fungerar alltså som ett 'vanligt' fondbolag, men med statlig förvaltning.
		</p>
		<p>
			På denna sida kan du se hur AP-fonderna investerat specifikt i fossila bränslen, förbjudna vapen och tobaksbolag. <a target="_blank" href="/qa#measures">Här kan du läsa mer om de olika måtten. </a>
		</p>

			<h2>Utmaningar angående hållbarhet för Premiepensionssystemet och AP7</h2>
		<p>
			Pensionsmyndigheten har valt att sortera fonder i flera kategorier där <a target="_blank" href="http://www.pensionsmyndigheten.se/VadArEnMiljoEtiskFond.html">miljö och etiska</a> kategorin är intressant utifrån hållbarhetsaspekten. Inom kategorin miljö/etiska fonder finns omkring 110-120 fonder.  Man kan även tänka sig att investera mot specifika branscher som bör ge bra avkastning på grund av klimatförändringarna och samtidigt gör gott. Om fonden inte klassas som etisk så kräver det mer kunskaper för att kunna avgöra hur pass hållbar den är och här kan givetvis Sparahållbarts ranking hjälpa till.
			Sparahållbart är dock kritiska till att Pensionsmyndigheten använder Hållbarhetsprofilen som märkning, <mark>se vidare här-xxxx (LÄGG IN LÄNK HÄR TILL TEXT).</mark>
		</p>
		<p>
			AP–fonderna har fått en mer hållbar profil de senaste åren, men AP7 har t.ex. fossila bolag i sin portfölj. Exxon mobile är största innehav sista mars 2016. Exxon mobile är en av de företag som har störst tillgångar av fossila bränslen i lager. Att förbränna dessa skulle addera över 8 miljarder ton koldioxid till atmosfären, 160 gånger mer än hela Sverige släpper ut per år. Exxon mobile har också många andra tveksamheter på sitt samvete se <a href="http://www.democracynow.org/2012/5/7/exxonmobils_dirty_secrets_from_indonesia_to" target="_blank">intervju</a> med Steve Coll, Amerikansk Pulitzer prisvinnare.
		</p>
	</div>
	<div class="section">
		<h1>
			Tjänstepension
		</h1>
		<p>
			Utöver den statliga premiepensionen har många en pension kopplat till sitt arbete, en tjänstepension, där arbetsgivare avsätter kapital som arbetstagaren i många fall aktivt kan placera. För att få en någorlunda överblick av din samlade pension så är ett bra tips att använda sidan <a href="http://www.minpension.se" target="_blank">minpension</a> som är ett statligt samarbete med pensionsbolagen.
		</p>
		<p>
			Hur tjänstepensionen fungerar beror på vilket avtal arbetsgivaren har med medarbetare eller fackförbund. Ofta avsätts under åren betydande belopp vilket gör det viktigt att då och då sätta sig in i hur kapitalet är placerat. Grovt sett kan tjänstepensionen delas in i två delar, en del som du kan välja placering på själv och en del som kan vara förmånsbestämd (med detta menas att du är garanterad en viss del av din slutlön i pension). För den del du själv kan bestämma över finns generellt två valmöjligheter, placering i traditionell försäkring eller fondplacering.
		</p>
		<p>
			Innan detta val görs behövs dock förvaltningsbolag väljas. Redan här är det viktigt att ta hållbarhetsaspekten i beaktning då bolagen är olika bra på denna typ av arbete. Söderberg och partners gjorde första gången i augusti 2014 en undersökning av flera stora kapitalförvaltare med avseende på kvaliteten i deras hållbarhetsarbete. Ett citat ur resultatet är:
		</p>
		<p>
			<em>”Folksam Liv, SPP och Swedbank får slutbetyget grönt medan Alecta, KPA och Skandia Liv får betyget gult. Swedbank och SPP får grönt betyg inom tre av fyra perspektiv och är därmed de som presterat allra bäst i analysen. AMF, Handelsbanken Liv, Länsförsäkringar Liv, Nordea Liv, SEB Gamla och SEB Nya får alla slutbetyget rött.”</em>
		</p>
		<p>
			Det finns givetvis flera aktörer ovan som har enstaka fondprodukter som får räknas som hållbara i flera aspekter och för att mer förstå vad Söderberg och partners har granskat samt resultatet av senare års undersökningar hänvisas till deras hemsida.
		</p>
		<p>
			I den traditionella försäkringen är du som sparare garanterad en viss avkastning och behöver ej vara aktiv i dina val. Beroende på konjunktur och hur börsen går så kan dock i vissa fall den garanterade avkastningen justeras. Den genomsnittliga avkastningen kan också bli lägre än om du själv placerar kapitalet i fonder. Alternativ två är att själv välja fonder som kapitalet skall placeras i. Här har du större möjlighet att påverka mer specifikt vad gäller risk, men kanske också hållbarhetsprofil på investeringarna. Du måste dock lägga mer tid själv.
		</p>
		<p>
			För att läsa mer om tjänstepension rekommenderas att titta på pensionsmyndighetens hemsida eller att göra en sökning på nätet för att hitta en specifik beskrivning av den variant som berör dig som arbetstagare.
		</p>
		<p>
			För de fonder där du kan välja så kan du använda <a href="<?php echo $this->url('funds') ?>">Sparahållbarts fondsök</a> för att förstå om fonden har placeringar i fossila bränslen, förbjudna vapen och tobaksbolag.
		</p>


	</div>


</div>
