<div class="container">
  <h1><?php echo $this->organisation->name ?></h1>
  <h2>Om organisationen</h2>
  <p><?php echo $this->organisation->info ?><p>
    <h3>Webbplats</h3>
  <p><a href="<?php echo $this->organisation->website ?>"><?php echo $this->organisation->website ?></a><p>
  <h3>Fondbolag som är medlemmar</h3>

  <?php foreach ($this->organisation->getFundCompanies() as $fundCompany): ?>

      <a class="btn btn-success" href="/fundcompany/<?php echo $this->translate($fundCompany->url) ?>"><?php echo $fundCompany->name ?></a>

  <?php endforeach?>
  </ul>

</div>
