<?php
$this->headTitle("Spara hållbart-skolan", 'PREPEND');

$this->headMeta()->appendName('description', $this->translate('Hur sparar man hållbart? Vad är det för skillnad på olika fonder?'));
?>
<div class="container">
	<section class="">
		<div id="school-header-pic-box" class="">
			<img src="/img/school/school_header.png" alt="spara hallbart skolan logo"/>
		</div>
		<p>Att förstå sig på det där med sparande och val av hur dina pengar ska investeras är inte alltid helt lätt. Sparahållbart-skolan syftar till att göra det hela lite lättare.</p>
		<p>Skolan kommer att uppdateras efter hand så att du som sparare ska kunna göra ett fondval som ligger i linje med just dina preferenser och mål.</p>
	</section>


	<section class="qa-section">
	<div class="">
			<h2>Sparahållbartskolan del 1: Fondsparande</h2>
			<p>
	    I denna del går vi igenom det som kan vara bra att veta gällande sparande. I nästa del riktar vi in oss mer specifikt mot hållbart sparande. Har du koll på olika sparprodukter och fondsparande?
			Gå till Del 2: Hållbart sparande.
			</p>
			<div class="row centered lesson-links">
				<div class="col-sm-3 col-xs-6">
					<a href="#">
						<img src="/img/school/aktiebox.png" />
						<br />
						Lektion 1 : risk
					</a>
				</div>
				<div class="col-sm-3 col-xs-6">
					<a href="#">
						<img src="/img/school/aktiebox.png" />
						<br />
						Lektion 1 : risk
					</a>
				</div>
				<div class="col-sm-3 col-xs-6">
					<a href="#">
						<img src="/img/school/aktiebox.png" />
						<br />
						Lektion 1 : risk
					</a>
				</div>
				<div class="col-sm-3 col-xs-6">
					<a href="#">
						<img src="/img/school/aktiebox.png" />
						<br />
						Lektion 1 : risk
					</a>
				</div>
			</div>

			<h2>Sparahållbartskolan del 2: Hållbart sparande</h2>
			<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>
			<ul>
				<li>
					<a href="#">Lorem ipsum dolor sit </a>
				</li>
				<li>
					<a href="#">Lorem ipsum dolor sit</a>
				</li>
			</ul>

	  </div>
	</section>
</div>
