<section class="qa-section container">
  <h2>Vanliga frågor</h2>
  <div class="row">
    <div class="col-sm-3 well">
    <ul>
      <li><a href="#categories">Kategorier</a></li>
      <li><a href="#levels">Nivå</a></li>
      <li><a href="#cat">Organisationer</a></li>
      <li><a href="#cat">Fondkategorier</a></li>
    </ul>
    </div>
    <div class="col-sm-9">
      <h3 id="categories">Kategorier</h3>
      <p>Det fem kategorierna finns för att göra en jämförelse på fondernas hållbarhet lättare. </p>
      <?php $rowCount = 0; ?>
      <?php foreach($accCategories as $cname => $category): ?>
        <?php if ($rowCount % 2 == 0 ) echo "<div class='row'>"; ?>
          <div class="col-sm-6 category-desc">
            <h4>
              <img class="symbol" src='/img/symbols/<?php echo $cname ?>.png'>
              <?php echo $category->name ?>
            </h4>
            <p>
              <?php echo $category->description ?>
            </p>
          </div>
        <?php if ($rowCount++ % 2 == 1 ) echo "</div>"; ?>
      <?php endforeach; ?>
      <?php if ($rowCount % 2 == 1 ) echo "</div>"; ?>

      <hr>


      <div class="row">
        <div class="col-sm-9">
          <h3 id="levels">Nivå</h3>
          <img class="qa-bar" src="/img/bar/bar7.png">
          <img class="qa-bar" src="/img/thin-bar/thinbar7.png">
          <p>Nivån beskriver hur fonden ligger till i kategorin och utgår från hur många volag som har i aktiell kategori. Nivån stigel enligt en logaritmisk modell för att kunna jämföra fonder med många och få innehav. </p>
        </div>
        <div class="col-sm-3 well">
          <h4>Nivåer</h4>
          <ul>
            <li>Nivå 10 - 0 bolag</li>
            <li>Nivå 9 - 1 bolag</li>
            <li>Nivå 8 - 2 bolag</li>
            <li>Nivå 7 - 3 bolag</li>
            <li>Nivå 6 - 4 bolag</li>
            <li>Nivå 5 - 5-9 bolag</li>
            <li>Nivå 4 - 10-19 bolag</li>
            <li>Nivå 3 - 20-29 bolag</li>
            <li>Novå 2 - 30-49 bolag</li>
            <li>Nivå 1 - 50- bolag</li>
          </ul>
        </div>
      </div>
    </div>

  </div>

</section>
