<?php
$this->headTitle("För fondbolag", 'PREPEND');
$this->headMeta()->appendName('description', ($this->translate('Alla fondbolag är välkomna att lista sina fonder på sparahållbart.se genom ett bas- eller premiummedlemskap. Bannerannonser finns även som möjlighet för att synas på sajten. ')));

 ?>
<div class="container">
  <h1>Att synas på sparahållbart.se</h1>
  <p>
    För er som är ett fondbolag eller är en annan relevant aktör kring hållbara investeringar har vi möjligheter för synlighet på sparahållbart.se.
  </p>
  <div class="row">
    <div class="col-md-8">

      <h2>Basmedlemskap - Lista dina fonder på sparahållbart.se</h2>
      <p>
        Det finns för alla fondbolag möjlighet att lista sina fonder i vårt verktyg. För att underhålla sidan och administrera fonddatan
        tar vi ut en avgift. Medlemskapet löper årsvis och ni som fondbolag skickar in fondinnehaven till oss på månadsbasis. Har ni fond-i-fond-lösningar diskuterar vi ett sätt att betygsätta era fonder om det går att ta fram underliggande värdepappersinnehav.
        Läs mer om basmedlemskap i dokumentet Product sheet.
      </p>
      <h2>Premiummedlemskap - featured brand</h2>
      <p>
        För er som vill ha en ökad synlighet på sparahållbart.se finns det möjlighet till det genom ett premium-medlemskap. I det ingår
        synlighet av er logotyp samt redaktionellt fria ytor för er på sajten att utforma   som ni själva vill.
        Läs mer om premium-fondbolag i dokumentet Product sheet.
      </p>
      <h2>Displayannonsering / Bannerannonsering</h2>
      <p>
        För er som vill synas mot en publik som är intresserade av hållbartsparande och aktivt val av fonder kan vi även erbjuda bannerannonser.
        Läs mer om bannerannonser i dokumentet Banner advertising.
      </p>
      <h2>Kontakt</h2>
      Kontaktperson för medlemskap och annonsering är Stefan Carlsson, VD Sparfabriken. Stefan nås på
      <a href="mailto:&#115;&#116;&#101;&#102;&#97;&#110;&#64;&#115;&#112;&#97;&#114;&#102;&#97;&#98;&#114;&#105;&#107;&#101;&#110;&#46;&#115;&#101;">
        epost
      </a>
      eller telefon +46 (0) 70-227 12 50.
    </div>
    <div class="col-md-4">
      <h2>Dokument (PDF)</h2>
      <ul class="list-unstyled">
        <li><a href="/documents/test_product_sheet.pdf" target="blank" class="btn btn-warning file-button" role="button"> <span class="glyphicon glyphicon-file glyphicon-lg"></span>Product sheet (PDF)</a></li>
        <li><a href="#" target="blank" class="btn btn-warning file-button" role="button"> <span class="glyphicon glyphicon-file glyphicon-lg"></span>Banner ads (PDF)</a></li>
        <li><a href="/documents/Pricessparahallbartse.pdf" target="blank" class="btn btn-warning file-button" role="button"> <span class="glyphicon glyphicon-file glyphicon-lg"></span>Prices (PDF)</a></li>
      </ul>
    </div>
  </div>
</div>
