<?php
$this->headTitle("AP-fonderna", 'PREPEND');
$this->headMeta()->appendName('description', $this->translate('Se hur de statliga pensionsfonderna AP-fonderna AP1, AP2, AP3, AP4 och AP7 placerar i vapenbolag, kol, olja, gas, tobak, alkohol och spelbolag. '));
?>

<div class="fund-company-page">
  <div class="fund-company-header">
    <div class="container">
      <h1 class="">
        <strong>AP-fonderna</strong>
      </h1>
      <p>
        AP-fonderna är ett samlingsnamn för de olika allmänna pensionsfonder som finns i Sverige.
      </p>
      <p>
        Första, andra, tredje och fjärde AP-fonden (AP1-AP4) tillhör
        inkomstpensionssystemet och är så kallade buffertfonder. Rollen för dessa AP-fonder
        är att jämna ut eventuellt underskott mellan inbetalningar av pensionsavgifter och utbetalningar
        av pensioner. Första till fjärde AP-fondernas uppgift är även att bidra till pensionssystemets
        långsiktiga finansiering.
      </p>

      <p>
        Sjunde AP-fonden (AP7) är den AP-fond som flest känner till. denna fond är det statliga
        alternativt i premiepensionssystemet (tidigare kallat PPM). Sjunde AP-fondens tillgångar kommer huvudsakligen från sparare som
        avstått från att aktivt välja fonder. Sjunde AP-fonden fungerar på så sätt lkt ett 'vanligt' fondbolag men med statlig
        förvaltning.
      </p>

      <p>
        På denna sida kan du se hur AP-fonderna investerat specifikt i fossila bränslen, förbjudna vapen och tobaklbolag.
        <a href="/qa#measures">Här kan du läsa mer om de olika måtten. </a>
      </p>
    </div>
  </div>

  <section class="fund-company-funds">
    <div class="container">
      <?php
        echo $this->partial(
            'fund-list',
              array(
                'funds'        => $funds,
                'paginated'    => 'false'
            ));
      ?>
    </div>
  </section>
</div>
