<?php

$this->headScript()
->prependFile($this->basePath() . '/vendor/selectize/dist/js/standalone/selectize.min.js')
->prependFile($this->basePath() . '/vendor/chartjs/Chart.min.js')
->appendFile($this->basePath() . '/js/funds.js')
->appendFile($this->basePath() . '/js/sustainability-chart.js');

if (isset($query['order'])) {
  $order = $query['order'];
} else {
  $order = 'ASC';
}
if (isset($query['sort'])) {
  $sortby = $query['sort'];
} else {
  $sortby = "sustainability";
}

/* Filter funds form */
$form->setAttribute('method', 'GET');
$form->setAttribute('action', $this->url('funds', array(), array('query' => $query)));
$form->prepare();

/* Sustainability categories form */
$sform->setAttribute('method', 'POST');
$sform->setAttribute('action', $this->url('change-sustainability-categories'));
$sform->prepare();
$submit = $sform->get('submit');
$submit->setValue('Välj kategorier');

?>

  <section class="container fund-list">
    <div class="row">
      <div id="fund-filters" class="col-md-4 col-md-push-8 panel-group panel-box clearfix">
        <div class="filter-header">
          <h3>Begränsa sökresultaten: </h3>
          <p><?php echo $funds->getPages()->totalItemCount;?> fonder.</p>
        </div>
        <?php echo $this->form()->openTag($form) ?>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseQ">
                <?php echo $this->translate('Namnet innehåller') ?>
              </a>
            </h3>
          </div>

          <div id="collapseQ" class="panel-collapse collapse in">
            <div class="panel-body">
              <p><?php echo $this->translate('Sök på hela eller delar av fondnamnet.') ?></p>
              <div class="input-group">
                <?php echo $this->formRow($form->get('q')); ?>
              </div><!-- /input-group -->
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseSusScore">
                <?php echo $this->translate('Hållbarhetsnivå') ?>
              </a>
            </h3>
          </div>
          <div id="collapseSusScore" class="panel-collapse collapse <?php if ($form->get('sustainabilityscore')->getValue()) {echo " in ";} ?>">
            <div class="panel-body">
              <p><?php echo $this->translate('Välj vilka hållbarhetsnivåer du vill visa. 10 är högsta hållbarhet. ') ?></p>
              <div class="checkbox">
                <?php
                $this->formMultiCheckbox()->setSeparator('</div><div class="checkbox">');
                  echo $this->formMultiCheckbox($form->get('sustainabilityscore'));
                  ?>
                </div>
              </div>
            </div>
          </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseFondoutCategory">
                <?php echo $this->translate('Fondkategori') ?>
              </a>
            </h3>
          </div>

          <div id="collapseFondoutCategory" class="panel-collapse collapse <?php if ($form->get('fondoutcategory')->getValue()) {echo " in ";} ?>">
            <div class="panel-body">
              <p><?php echo $this->translate('Välj var i världen fonden äger sin majoritet av företag.') ?></p>
              <div class="checkbox">
                <?php
                $this->formMultiCheckbox()->setSeparator('</div><div class="checkbox">');
                  echo $this->formMultiCheckbox($form->get('fondoutcategory'));
                  ?>
                </div>
              </div>
            </div>
          </div>

          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseCompany">
                  <?php echo $this->translate('Fondbolag') ?>
                </a>
              </h3>
            </div>
            <div id="collapseCompany" class="panel-collapse collapse <?php if ($form->get('company')->getValue()) {echo " in ";} ?>">
              <div class="panel-body">
                <p><?php echo $this->translate(' Välj vilken bank eller fondbolags fonder du vill se.') ?></p>
                <?php echo $this->formSelect($form->get('company')) ?>
              </div>
            </div>
          </div>

          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseSize">
                  <?php echo $this->translate('Fondstorlek') ?>
                </a>
              </h3>
            </div>
            <div id="collapseSize" class="panel-collapse collapse <?php if ($form->get('size')->getValue()) {echo " in ";} ?>">
              <div class="panel-body">
                <p><?php echo $this->translate('Välj vilken storlek av fonder du vill se. Fonder som många personer äger är generellt större och nischade fonder mindre. ') ?></p>
                <div class="checkbox">
                  <?php
                  $this->formMultiCheckbox()->setSeparator('</div><div class="checkbox">');
                    echo $this->formMultiCheckbox($form->get('size'));
                    ?>
                  </div>
                </div>
              </div>
            </div>

          <?php echo $this->formHidden($form->get('category')) ?>
            <div class="search-fund-button pull-right">
              <?php echo $this->formSubmit($form->get('submit')->setValue('Uppdatera fondsökning')) ?>
            </div>
            <?php echo $this->form()->closeTag() ?>
            <br />
          </div>
          <div class="col-md-8 col-md-pull-4">
            <?php if (strcmp($sortby,'sustainability') == 0): ?>
              <?php echo $this->partial('sustainability-categories',
              array(
              'sform' => $this->sform,
              'sustainability' => $sustainability
              )
              ); ?>
            <?php endif; ?>


            <?php if (count($funds)): ?>


<div class="well well-sm">
  <div class="row">
    <p class="sortby-header">Sortera efter</p>
    <ul class="nav nav-pills pull-right sortby-buttons">

      <li class="dropdown <?php if (strcmp($sortby,'co2') == 0): echo ' active '; endif; ?>">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          CO<sub>2</sub>-utsläpp <?php if (strcmp($sortby,'co2') == 0): if ($order=='ASC'): echo ' (lägst till högst)'; else: echo ' (högst till lägst)'; endif; endif; ?><span class="caret"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
          <li><a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array(), array('query' => array('sort' => 'co2', 'order' => 'DESC')  + $query))); ?>">CO<sub>2</sub>-utsläpp (högst till lägst)</a></li>
          <li><a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array(), array('query' => array('sort' => 'co2', 'order' => 'ASC')  + $query))); ?>">CO<sub>2</sub>-utsläpp (lägst till högst)</a></li>
        </ul>
      </li>

      <li class="dropdown <?php if (strcmp($sortby,'sustainability') == 0): echo ' active '; endif; ?>">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          Hållbarhetsnivå <?php if (strcmp($sortby,'sustainability') == 0): if ($order=='ASC'): echo ' (lägst till högst)'; else: echo ' (högst till lägst)'; endif; endif; ?><span class="caret"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
          <li><a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array(), array('query' => array('sort' => 'sustainability', 'order' => 'DESC')  + $query))); ?>">Hållbarhetsnivå (högst till lägst)</a></li>
          <li><a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array(), array('query' => array('sort' => 'sustainability', 'order' => 'ASC')  + $query))); ?>">Hållbarhetsnivå (lägst till högst)</a></li>
        </ul>
      </li>
    </ul>
  </div>
</div>

<ul class="results">
  <?php foreach ($funds as $fund): ?>
    <li>
      <?php if (strcmp($sortby,'sustainability') == 0): ?>
        <div class="pull-right">
          <div class="pull-right sustainability-desc">
            <?php echo $this->translate('Hållbarhetsnivå') ?>
            <span class="sustainability-score"><strong><?php echo $fund->getSustainabilityScore()*10 ?></strong>/10</span>
            <span class="hidden-xs">
                <?php
                if ($fund->getSustainabilityScore() == 1): echo $this->translate('Hållbar fond enligt din sökning.');
                elseif ($fund->getSustainabilityScore() > 0.7): echo $this->translate('Fonden har ett fåtal ohållbara bolag.');
                elseif ($fund->getSustainabilityScore() > 0.5): echo $this->translate('Fonden har en stor del ohållbara bolag.');
                elseif ($fund->getSustainabilityScore() > 0.3): echo $this->translate('Fonden har en mycket stor del ohållbara bolag.');
                elseif ($fund->getSustainabilityScore()): echo $this->translate('Denna fond stämmer inte in på dina hållbarhetskriterier.');
                else: echo $this->translate('Denna fond har inte kunnat granskas.');
                endif;
              ?>
            </span>
          </div>

          <div class="chart-container pull-left">
            <canvas class="sustainability-chart" data-percentage="<?php echo $fund->getSustainabilityScore() ?>"></canvas>
          </div>

        </div>
      <?php endif;?>


        <?php if (strcmp($sortby,'co2') == 0): ?>
          <div class="pull-right">
          <img class="co2-meter-symbol" src="img/co2-symbol.png" alt="CO2-symbol" />
          <div class="co2-meter">

            <div class="co2-header">CO<sub>2</sub>-utsläpp</div>
            <?php if ($fund->co2Coverage > $fund->co2CoverageLimit): ?>
            <div class="co2-meter-number">
              <?php
                if ($fund->co2 > 100):
                  echo number_format($fund->co2, 0, ',', ' ');
                elseif ($fund->co2 < 10):
                  echo number_format($fund->co2, 2, ',', ' ');
                else:
                  echo number_format($fund->co2, 1, ',', ' ');
                endif;
              ?>
            </div>
            <div class="co2-meter-unit">gram CO<sub>2</sub>/kr</div>
            <?php else: ?>
            <div class="co2-meter-number co2-na">
              -
            </div>
            <div class="co2-meter-unit">Ej tillgängligt</div>
          <?php endif;?>
          </div>
        </div>
        <?php endif;?>


      <h3>
        <a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array('id' => $fund->id))) ?>" title="">
          <?php echo $this->translate($fund->name) ?>
        </a>
      </h3>

      <p class="hidden-xs"><?php echo $this->translate($fund->company->name) ?></p>
      <p>
        <span class="label label-primary"><?php echo $this->translate($fund->fondoutcategory->title) ?></span>
        <span class="label label-primary"><?php
          if ($fund->totalMarketValue <= 600000000) {
            echo $this->translate('Liten fond');
          } elseif ($fund->totalMarketValue >= 2500000000) {
            echo $this->translate('Stor fond');
          } else {
            echo $this->translate('Mellanfond');
          }
          ?>
        </span>
      </p>
    </li>
  <?php endforeach; ?>
</ul>

<?php else: ?>
  <h3><?php echo $this->translate('Vi kunde inte hitta några resultat med dina söktermer.') ?></h3>
  <br>
  <h4><?php echo $this->translate('Förslag') ?>:</h4>
  <ul>
    <li><?php echo $this->translate('Dubbelkolla din stavning') ?></li>
    <li><?php echo $this->translate('Använd mer generella söktermer') ?></li>
    <li><a href="/funds" class="btn btn-primary" role="button">Återställ sökning</a>


  </ul>

<?php endif; ?>

<?php if ($funds->getPages()->pageCount > 1): ?>
  <ul class="pagination pagination-centered">
    <!-- Previous page link -->
    <?php if (isset($funds->getPages()->previous)): ?>
      <li>
        <a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array(), array('query' => array('page' => $funds->getPages()->previous) + $query))); ?>">
          &laquo;
        </a>
      </li>
      <?php
      else: ?>
      <li class="disabled">
        <a href="#">
          &laquo;
        </a>
      </li>
    <?php endif; ?>
    <!-- Numbered page links -->
    <?php foreach ($funds->getPages()->pagesInRange as $page): ?>
      <?php if ($page != $funds->getPages()->current): ?>
        <li>
          <a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array(), array('query' => array('page' => $page)  + $query))); ?>">
            <?php echo $page; ?>
          </a>
        </li>
      <?php else: ?>
        <li class="active">
          <a href="#"><?php echo $page; ?></a>
        </li>
      <?php endif; ?>
    <?php endforeach; ?>

    <!-- Next page link -->
    <?php if (isset($funds->getPages()->next)): ?>
      <li>
        <a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array(), array('query' => array('page' => $funds->getPages()->next) + $query))); ?>">
          &raquo;
        </a>
      </li>
    <?php else: ?>
      <li class="disabled">
        <a href="#">
          &raquo;
        </a>
      </li>
    <?php endif; ?>
  </ul>
<?php endif; ?>
</div>
</section>
