<?php

$this->headScript()
->prependFile($this->basePath() . '/vendor/selectize/dist/js/standalone/selectize.min.js')
->appendFile($this->basePath() . '/js/funds.js');

if (isset($query['order'])) {
  $order = $query['order'];
} else {
  $order = 'ASC';
}

if ($order == 'ASC') {
  $reverseorder = 'DESC';
} else {
  $reverseorder = 'ASC';
}

if (isset($query['sort'])) {
  $sortby = $query['sort'];
} else {
  $sortby = "name";
}


/* Filter funds form */
$form->setAttribute('method', 'GET');
$form->setAttribute('action', $this->url('funds', array(), array('query' => $query)));
$form->prepare();

?>

  <section class="container fund-list">
    <div class="row">
      <div id="fund-filters" class="col-md-4 col-md-push-8 panel-group panel-box clearfix">
        <div class="filter-header">
          <h3>Begränsa sökresultaten: </h3>
          <p><?php echo $funds->getPages()->totalItemCount;?> fonder.</p>
        </div>
        <?php echo $this->form()->openTag($form) ?>

        
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseFondoutCategory">
                <?php echo $this->translate('Fondkategori') ?>
              </a>
            </h3>
          </div>

          <div id="collapseFondoutCategory" class="panel-collapse collapse in"><!--class="panel-collapse collapse <?php if ($form->get('fondoutcategory')->getValue()) {echo " in ";} ?>">-->
            <div class="panel-body">
              <p><?php echo $this->translate('Välj var i världen fonden äger sin majoritet av företag.') ?></p>
              <div class="checkbox">
                <?php
                $this->formMultiCheckbox()->setSeparator('</div><div class="checkbox">');
                  echo $this->formMultiCheckbox($form->get('fondoutcategory'));
                  ?>
                </div>
              </div>
            </div>
          </div>

          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseCompany">
                  <?php echo $this->translate('Fondbolag') ?>
                </a>
              </h3>
            </div>
            <div id="collapseCompany" class="panel-collapse collapse <?php if ($form->get('company')->getValue()) {echo " in ";} ?>">
              <div class="panel-body">
                <p><?php echo $this->translate(' Välj vilken bank eller fondbolags fonder du vill se.') ?></p>
                <?php echo $this->formSelect($form->get('company')) ?>
              </div>
            </div>
          </div>

          <?php echo $this->formHidden($form->get('category')) ?>
            <div class="search-fund-button pull-right">
              <?php echo $this->formSubmit($form->get('submit')->setValue('Uppdatera fondsökning')) ?>
            </div>
            <?php echo $this->form()->closeTag() ?>
            <br />
          </div>
          <div class="col-md-8 col-md-pull-4">
            <?php if (count($funds)): ?>


<div class="well well-sm">
  <div class="row">
    <p class="sortby-header">Ranka efter</p>
    <button class="btn"><a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array(), array('query' => array('sort' => 'name', 'order' => ($sortby == 'name' ? $reverseorder : 'ASC'))  + $query))); ?>">A-Z</a></button>
    <button class="btn"><a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array(), array('query' => array('sort' => 'weapon', 'order' => ($sortby == 'weapon' ? $reverseorder : 'ASC'))  + $query))); ?>">WEAPON</a></button>
    <button class="btn"><a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array(), array('query' => array('sort' => 'fossil', 'order' => ($sortby == 'fossil' ? $reverseorder : 'ASC'))  + $query))); ?>">FOSSIL</a></button>
    <button class="btn"><a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array(), array('query' => array('sort' => 'altoga', 'order' => ($sortby == 'altoga' ? $reverseorder : 'ASC'))  + $query))); ?>">ALTOGA</a></button>

  </div>
</div>

<ul class="results">
  <?php foreach ($funds as $fund): ?>
    <li>  
  
      <div class="pull-right">
        <?php 
          echo "WEAPON <strong>" . $fund->getWeaponCompanies() . " </strong>" . 
               "FOSSIL <strong>" . $fund->getFossilCompanies() . " </strong>" . 
               "ALTOGA <strong>" . $fund->getAlToGaCompanies(). " </strong>"  ;
        ?>    
      </div>

      <h3>
        <a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array('id' => $fund->url))) ?>" title="">
          <?php echo $this->translate($fund->name) ?>
        </a>
      </h3>
      <p class="hidden-xs"><?php echo $this->translate($fund->company->name) ?></p>
      <p>
        
        <a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array(), array('query' => array('fondoutcategory[]' => $fund->fondoutcategory->id)))); ?>">
          <span class="label label-primary"><?php echo $this->translate($fund->fondoutcategory->title) ?></span>
        </a>
      </p>

    </li>
  <?php endforeach; ?>
</ul>

<?php else: ?>
  <h3><?php echo $this->translate('Vi kunde inte hitta några resultat med dina söktermer.') ?></h3>
  <br>
  <h4><?php echo $this->translate('Förslag') ?>:</h4>
  <ul>
    <li><?php echo $this->translate('Dubbelkolla din stavning') ?></li>
    <li><?php echo $this->translate('Använd mer generella söktermer') ?></li>
    <li><a href="/funds" class="btn btn-primary" role="button">Återställ sökning</a>


  </ul>

<?php endif; ?>

<?php if ($funds->getPages()->pageCount > 1): ?>
  <ul class="pagination pagination-centered">
    <!-- Previous page link -->
    <?php if (isset($funds->getPages()->previous)): ?>
      <li>
        <a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array(), array('query' => array('page' => $funds->getPages()->previous) + $query))); ?>">
          &laquo;
        </a>
      </li>
      <?php
      else: ?>
      <li class="disabled">
        <a href="#">
          &laquo;
        </a>
      </li>
    <?php endif; ?>
    <!-- Numbered page links -->
    <?php foreach ($funds->getPages()->pagesInRange as $page): ?>
      <?php if ($page != $funds->getPages()->current): ?>
        <li>
          <a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array(), array('query' => array('page' => $page)  + $query))); ?>">
            <?php echo $page; ?>
          </a>
        </li>
      <?php else: ?>
        <li class="active">
          <a href="#"><?php echo $page; ?></a>
        </li>
      <?php endif; ?>
    <?php endforeach; ?>

    <!-- Next page link -->
    <?php if (isset($funds->getPages()->next)): ?>
      <li>
        <a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array(), array('query' => array('page' => $funds->getPages()->next) + $query))); ?>">
          &raquo;
        </a>
      </li>
    <?php else: ?>
      <li class="disabled">
        <a href="#">
          &raquo;
        </a>
      </li>
    <?php endif; ?>
  </ul>
<?php endif; ?>
</div>
</section>
