<?php
$this->headTitle("Om sparahållbart.se", 'PREPEND');
$this->headMeta()->appendName('description', $this->translate('Om sparahallbart.se'));
?>

<div class="mid-section-image intro-qa">
  <div class="container"><h1 id="top">Om tjänsten sparahallbart.se</h1></div>
</div>
<section class="container qa-section">
  <div class="row">
    <div class="col-md-9">
			<p>“Sparahållbart.se - fondjämförelser ur ett hållbarhetsperspektiv har aldrig varit enklare” hjälper dig att på ett enkelt sätt ta reda på hur dina fonder/ de fonder du är intresserad av arbetar med hållbarhet för att sedan kunna jämföra dessa med andra fonder. Fondval och hållbarhetspreferenser är självklart helt upp till dig. </p>
			<p>Det finns idag ingen standarddefinition som beskriver när en fond är hållbar (se vidare i fondskolan nedan). Varje fondbolag kan välja sina egna kriterier eller så köper aktörerna in analyser som säger vilka aktier som t.ex. skall exkluderas. Därför är det intressant att ha en oberoende part som listar och rankar hållbara fonder. </p>
			<p>En aktör som funnits över 10 år på marknaden är Swesif. De är en intresseorganisation där medlemmarna är fondbolag och kapitalförvaltare. Med hjälp av hållbarhetsprofilen illustrerar Swesif fondernas hållbarhetsstrategi och metod. Tyvärr är tjänsten svår att använda och det kräver att läsaren är kunnig för att kunna dra slutsatser om hur hållbara fonderna egentligen är.  Många fondbolag har också valt att lista alla sina fonder oavsett om de har en hållbar profil eller inte. Vill man ha en hållbar och etisk fond utan fossilinvesteringar kan det vara svårt att använda hållbarhetsprofilen och Swesif lista. </p>
			<p>En annan aktör som nyligen (Mars 2016) släppte ett verktyg för jämförelse av hållbarheten hos fonder är Morningstar. Morningstar köper in hållbarhetsinformation för de enskilda aktieinnehaven i fonderna från en tredje part och räknar sedan ut ett betyg för varje fond. Inom varje bransch normaliseras sedan betyget. Detta gör att det tyvärr inte går att jämföra t.ex. en sverigefond med en globalfond eller rysslandfond. Betyget visar inte heller om fonder t.ex. har innehav i fossilbolag. </p>
			<p>Här kan sparahållbart.se hjälpa till då tjänsten illustrerar just innehaven och även så att de är jämförbara mellan branscher. </p>
			<p>I första hand rekommenderas Sparahållbart-tjänsten att användas för att kolla upp de fonder du sparar i idag. Genom att utgå från dina nuvarande fonder och jämföra dessa med alternativa fonder inom förslagsvis samma fondkategori kan du på ett enkelt sätt se hur hållbara dina fonder är i jämförelse med andra fonder. Om du är nöjd med hur dina fonder investerar utifrån en hållbarhetssynpunkt finns det ingen anledning att byta fonder. Om fonderna däremot investerat mycket inom en bransch som du som sparare inte önskar stå bakom kan det vara läge att byta till en fond som passar dig bättre.</p>
			<p>Tjänsten kan även användas för att hitta nya fonder att börja spara dina pengar i.</p>
			<p>Värt att tänka på är att det utöver hållbarhetsbiten finns många parametrar som är viktiga när det kommer till ditt val av fond, t.ex. risknivå och avgift.</p>
      <h2 id="measures">Våra mått</h2>
      <p>För att du ska kunna hitta en fond som ligger i linje med dina hållbarhetspreferenser kan du på Sparahållbart.se välja att jämföra dina fonder utifrån fem olika hållbarhetsmått/kategorier.</p>      <?php $rowCount = 0; ?>
      <?php foreach($accCategories as $cname => $category): ?>
        <?php if ($rowCount % 2 == 0 ) echo "<div class='row'>"; ?>
          <div class="col-sm-6 category-desc">
            <img class="category-image" src='/img/qa/<?php echo $cname ?>.jpg' alt="Category image <?php echo $cname ?>">
            <h3>
              <img class="symbol" src='/img/symbols/<?php echo $cname ?>.png' alt="<?php echo $cname ?> symbol">
              <?php echo $category->name ?>
            </h3>
            <p>
              <?php echo $category->description ?>
            </p>          </div>
        <?php if ($rowCount++ % 2 == 1 ) echo "</div>"; ?>
      <?php endforeach; ?>
      <?php if ($rowCount % 2 == 1 ) echo "</div>"; ?>
      <a href="<?php echo $this->url('funds') ?>" class="btn btn-primary">Gå till fondsök</a>
    </div>
  </div>
</section>
