<?php

$this->headScript()
  ->prependFile($this->basePath() .
  '/vendor/selectize/dist/js/standalone/selectize.min.js')
  ->appendFile($this->basePath() . '/js/fundprofile.js');

$thincategory = array("alcohol", "tobacco", "gambling")
?>
<section class="container fund-page">
  <div class="row centered-column header">
    <div class="col-md-4">
      <p>Fond</p>
    </div>
    <div class="col-md-3">
      <p>Hållbarhet</p>
    </div>
    <div class="col-md-3">
      <p>Fondinformation</p>
    </div>
    <div class="col-md-2">
      <a class="btn btn-primary btn-xs pull-right" href="<?php echo $this->backuri; ?>">
        Tillbaka till fondsök
      </a>
    </div>
  </div>

  <div role="tabpanel">

    <!-- Nav tabs -->
    <div class="row info">
      <div class="col-md-4">
        <?php echo  ($fund->fundCompany->premium) ? "<img class='fund-logo' src='/img/fund-company/logo/" . $fund->fundCompany->id . ".png' alt='" . $fund->fundCompany->name . " logo'>" : "" ?>
        <h2><?php echo $this->escapeHtml($fund->name) ?></h2>
      </div>
      <div class="col-md-3 bar-tabs">
        <ul class="nav nav-tabs" role="tablist">
          <li class="active" data-toggle='tooltip' title='<?php echo $accCat['fossil']->name ?>'><a href="#fossil" aria-controls="fossil" role="tab" data-toggle="tab"><img src="/img/bar/bar<?php echo $fund->measures->getMeasureScore('fossil')?>.png" class="bar"><br><img class="round-symbol" src="/img/symbols/fossil.png"></a><div class="arrow-up arrow-box"></div></li>
          <li data-toggle='tooltip' title='<?php echo $accCat['weapon']->name ?>'><a href="#weapon" aria-controls="weapon" role="tab" data-toggle="tab"><img src="/img/bar/bar<?php echo $fund->measures->getMeasureScore('weapon')?>.png" class="bar"><br><img class="round-symbol" src="/img/symbols/weapon.png"></a><div class="arrow-up arrow-box"></div></li>
          <li class="thintab"  data-toggle='tooltip' title='<?php echo $accCat['alcohol']->name ?>'><a href="#alcohol" aria-controls="alcohol" role="tab" data-toggle="tab"><img src="/img/thin-bar/thinbar<?php echo $fund->measures->getMeasureScore('alcohol')?>.png" class="thin-bar"><br><img class="thin-symbol" src="/img/symbols/alcohol.png"></a><div class="arrow-up arrow-box"></div></li>
          <li class="thintab"  data-toggle='tooltip' title='<?php echo $accCat['tobacco']->name ?>'><a href="#tobacco" aria-controls="tobacco" role="tab" data-toggle="tab"><img src="/img/thin-bar/thinbar<?php echo $fund->measures->getMeasureScore('tobacco')?>.png" class="thin-bar"><br><img class="thin-symbol" src="/img/symbols/tobacco.png"></a><div class="arrow-up arrow-box"></div></li>
          <li class="thintab"  data-toggle='tooltip' title='<?php echo $accCat['gambling']->name ?>'><a href="#gambling" aria-controls="gambling" role="tab" data-toggle="tab"><img src="/img/thin-bar/thinbar<?php echo $fund->measures->getMeasureScore('gambling')?>.png" class="thin-bar"><br><img class="thin-symbol" src="/img/symbols/gambling.png"></a><div class="arrow-up arrow-box"></div></li>
        </ul>
      </div>
      <div class="col-md-3 centered-column">
        <a class="fundinfo-btn btn btn-xs" href="/fundcompany/<?php echo $this->translate($fund->company->url) ?>">
            <?php echo $this->translate($fund->company->name) ?>
        </a>
        <a class="fundinfo-btn btn btn-xs" href="<?php echo $this->escapeHtmlAttr($this->url('funds', array(), array('query' => array('fondoutcategory[]' => $fund->fondoutcategory->id)))); ?>">
          <?php echo $this->translate($fund->fondoutcategory->longName) ?>
        </a>
        <?php echo (in_array('Avanza', $fund->getBankArray())) ? "<p class='bank-availible'>Fonden finns att köpa på <img src='/img/avanza.png' alt='Avanza logo' class='bank-logo'></p>" : "" ?>
      </div>
      <div class="col-md-2">
        <br>
        <img class="round-symbol" src="/img/gray-symbols/value.png" alt="Value">
        <br>
        1 år <span class="<?php echo ($fund->measures->nav1year < 0) ? "negative" : "positive";?> "><?php echo is_null($fund->measures->nav1year) ? '-' : ((($fund->measures->nav1year < 0) ? "" : "+") . number_format($fund->measures->nav1year, 0) . "%") ?> </span><br>
        3 år <span class="<?php echo ($fund->measures->nav3year < 0) ? "negative" : "positive";?> "><?php echo is_null($fund->measures->nav3year) ? '-' : ((($fund->measures->nav3year < 0) ? "" : "+") . number_format($fund->measures->nav3year, 0) . "%") ?> </span><br>
        5 år <span class="<?php echo ($fund->measures->nav5year < 0) ? "negative" : "positive";?> "><?php echo is_null($fund->measures->nav5year) ? '-' : ((($fund->measures->nav5year < 0) ? "" : "+") . number_format($fund->measures->nav5year, 0) . "%") ?> </span><br>
      </div>
    </div>

    <!-- Tab panes -->
    <div class="row content">
      <div class="tab-content measure-tabs">
        <?php foreach ($companies as $category => $ccompanies): ?>
          <div role="tabpanel" class="tab-pane <?php echo ($category == 'fossil') ? 'active' : '' ?>" id="<?php echo $category ?>">
            <div class="row">
              <div class="col-sm-6 centered-column measure-tabs-first-column">
                <h3>Ditt valda mått är: <strong><?php echo mb_strtoupper($accCat[$category]->name, 'UTF-8') ?></strong></h3>
                <div class="row">
                  <div class="col-md-4 centered-column" data-toggle='tooltip' title='<?php echo $fund->measures->getMeasureScore($category) ."/10. " ?>Fonden har investerat i <?php echo (call_user_func(array($this->fund, 'get' . $category . 'Companies'))) ?> bolag med <?php echo strtolower($accCat[$category]->name) ?>.'>
                    <img src="/img/<?php echo (in_array($category, $thincategory) ? "thin-" : "" )?>bar/<?php echo (in_array($category, $thincategory) ? "thin" : "" )?>bar<?php echo $fund->measures->getMeasureScore($category);?>.png" class="<?php echo (in_array($category, $thincategory) ? "thin-" : "" )?>bar">
                    <br>
                    <img class="<?php echo (in_array($category, $thincategory) ? "thin-" : "" )?>symbol" src="/img/symbols/<?php echo $category ?>.png">
                    <br>
                    <p><?php echo $this->escapeHtml($fund->name) ?></p>
                  </div>

                  <div class="col-md-4 centered-column" data-toggle='tooltip' title='<?php echo $avgcategory->getMeasureScore($category) ."/10. " ?>Fondkategorin <?php echo $this->fund->fondoutCategory->longName ?>er har i snitt investerat i <?php echo (call_user_func(array($this->avgcategory, 'get' . $category . 'Companies'))) ?> bolag med <?php echo strtolower($accCat[$category]->name) ?>.'>
                    <img src="/img/<?php echo (in_array($category, $thincategory) ? "thin-" : "" )?>bar/<?php echo (in_array($category, $thincategory) ? "thin" : "" )?>bar<?php echo $avgcategory->getMeasureScore($category)?>.png" class="<?php echo (in_array($category, $thincategory) ? "thin-" : "" )?>bar">
                    <br>
                    <img class="<?php echo (in_array($category, $thincategory) ? "thin-" : "" )?>symbol" src="/img/symbols/<?php echo $category ?>.png">
                    <br>
                    <p>Snitt <?php echo $this->translate($fund->fondoutcategory->longName) ?>er</p>
                  </div>
                  <div class="col-md-4 centered-column" data-toggle='tooltip' title='<?php echo $avgallfunds->getMeasureScore($category) ."/10. " ?>Snittet för alla fonder är att ha investerat i <?php echo (call_user_func(array($this->avgallfunds, 'get' . $category . 'Companies'))) ?> bolag med <?php echo strtolower($accCat[$category]->name) ?>.'>
                    <img src="/img/<?php echo (in_array($category, $thincategory) ? "thin-" : "" )?>bar/<?php echo (in_array($category, $thincategory) ? "thin" : "" )?>bar<?php echo $avgallfunds->getMeasureScore($category)?>.png" class="<?php echo (in_array($category, $thincategory) ? "thin-" : "" )?>bar">
                    <br>
                    <img class="<?php echo (in_array($category, $thincategory) ? "thin-" : "" )?>symbol" src="/img/symbols/<?php echo $category ?>.png">
                    <p>Snitt alla fonder</p>
                  </div>
                </div>
                <div class="row better-worse-row">
                  <span class='better-worse <?php if($fund->measures->getMeasureScore($category) > $avgcategory->getMeasureScore($category)) { echo "better'>" . "Fonden är bättre än snittet för fondkategorin."; } elseif ($fund->measures->getMeasureScore($category) == $avgcategory->getMeasureScore($category)) { echo "better'>" . "Fonden är samma som snittet för fondkategorin."; } else { echo "worse'>" . "Fonden är sämre än snittet för fondkategorin."; }?></span>
                  <br>
                  <span class='better-worse <?php if($fund->measures->getMeasureScore($category) > $avgallfunds->getMeasureScore($category)) { echo "better'>" . "Fonden är bättre än snittet för alla fonder."; } elseif ($fund->measures->getMeasureScore($category) == $avgallfunds->getMeasureScore($category)) { echo "better'>" . "Fonden är samma som snittet för alla fonder."; } else { echo "worse'>" . "Fonden är sämre än snittet för alla fonder."; }?></span>
                </div>
              </div>
              <div class="col-sm-6 measure-tabs-second-column">
                <?php echo $this->partial('example-companies', array('category' => $category, 'accCat' => $accCat, 'ccompanies' => $ccompanies)); ?>
              </div>
            </div>
          </div>
        <?php endforeach; ?>
      </div>
      <div class="col-md-12 premium-fund-info">
        <?php if ($fund->fundCompany->premium): ?>
          <h3>Om fonden </h3>
          <p>
            <?php echo $fund->info ?>
          </p>
          <h3>Om fondbolaget </h3>
          <p>
            <?php echo $fund->company->info ?>
          </p>
          <h3>Fondbolaget är med i följande organisationer</h3>
          <ul>
            <?php foreach($this->fund->fundCompany->organisations as $organisation): ?>
              <li><?php echo $organisation->name; ?></li>
            <?php endforeach; ?>
          </ul>
        <?php endif;?>
    </div>
    </div>
  </div>

  <!-- Start fund company funds -->
  <?php if($fund->fundCompany->premium): ?>
    <div class="row alternate-funds">
      <div class="alternate-funds-header col-md-12">
        <h3 class="centered-column"><?php echo mb_strtoupper("Andra fonder från " . $fund->fundCompany->name, 'UTF-8')  ?></h3>
      </div>

      <?php $i = 1; ?>
      <?php foreach ($fCompanyFunds as $fund): ?>
        <div class="col-md-6 alternate-fund">
          <div class="row">
            <div class="col-md-7">
              <?php echo  ($fund->fundCompany->premium) ? "<img class='fund-logo' src='/img/fund-company/logo/" . $fund->fundCompany->id . ".png' alt='" . $fund->fundCompany->name . " logo'>" : "" ?>
              <h4>
                <a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array('id' => $fund->url))) ?>" title="" target="_blank">
                  <?php echo $this->translate($fund->name) ?>
                </a>
              </h4>
            </div>
            <div class="col-md-1 centered-column">
              <?php echo "<img class='bar' src='/img/bar/bar" . $fund->measures->getMeasureScore('fossil') . ".png'>"    ?>
              <img class="round-symbol" src="/img/symbols/fossil.png">
            </div>
            <div class="col-md-1 centered-column">
              <?php echo "<img class='bar' src='/img/bar/bar" . $fund->measures->getMeasureScore('weapon') . ".png'>"    ?>
              <img class="round-symbol" src="/img/symbols/weapon.png">
            </div>
            <div class="col-md-3">
              <?php echo "<img class='thin-bar' src='/img/thin-bar/thinbar" . $fund->measures->getMeasureScore('alcohol') . ".png'>" ?>
              <?php echo "<img class='thin-bar' src='/img/thin-bar/thinbar" . $fund->measures->getMeasureScore('tobacco') . ".png'>"   ?>
              <?php echo "<img class='thin-bar' src='/img/thin-bar/thinbar" . $fund->measures->getMeasureScore('gambling'). ".png'>"   ?>
              <br>
              <img class="thin-symbol" src="/img/symbols/alcohol.png">
              <img class="thin-symbol" src="/img/symbols/tobacco.png">
              <img class="thin-symbol" src="/img/symbols/gambling.png">
            </div>
          </div>
        </div>

        <?php if ($i++ == 8) break; ?> <!-- Limit to 8 funds in list -->
      <?php endforeach; ?>
    </div>
  <?php endif; ?>
  <!-- End fund company funds -->
  <!-- Start category funds -->
  <div class="row alternate-funds">
    <div class="alternate-funds-header col-md-12">
      <h3 class="centered-column"><?php echo mb_strtoupper("Andra " . $fund->fondoutCategory->longName . "er", 'UTF-8')  ?></h3>
    </div>

    <?php $i = 1; ?>
    <?php foreach ($categoryFunds as $fund): ?>
      <div class="col-md-6 alternate-fund">
        <div class="row">
          <div class="col-md-7">
            <?php echo  ($fund->fundCompany->premium) ? "<img class='fund-logo' src='/img/fund-company/logo/" . $fund->fundCompany->id . ".png' alt='" . $fund->fundCompany->name . " logo'>" : "" ?>
            <h4>
              <a href="<?php echo $this->escapeHtmlAttr($this->url('funds', array('id' => $fund->url))) ?>" title="" target="_blank">
                <?php echo $this->translate($fund->name) ?>
              </a>
            </h4>
            1 år <span class="<?php echo ($fund->measures->nav1year < 0) ? "negative" : "positive";?> "><?php echo is_null($fund->measures->nav1year) ? '-' : ((($fund->measures->nav1year < 0) ? "" : "+") . number_format($fund->measures->nav1year, 0) . "%") ?> </span><br>
            3 år <span class="<?php echo ($fund->measures->nav3year < 0) ? "negative" : "positive";?> "><?php echo is_null($fund->measures->nav3year) ? '-' : ((($fund->measures->nav3year < 0) ? "" : "+") . number_format($fund->measures->nav3year, 0) . "%") ?> </span><br>
            5 år <span class="<?php echo ($fund->measures->nav5year < 0) ? "negative" : "positive";?> "><?php echo is_null($fund->measures->nav5year) ? '-' : ((($fund->measures->nav5year < 0) ? "" : "+") . number_format($fund->measures->nav5year, 0) . "%") ?> </span><br>          </div>
          <div class="col-md-1 centered-column">
            <?php echo "<img class='bar' src='/img/bar/bar" . $fund->measures->getMeasureScore('fossil') . ".png'>"    ?>
            <img class="round-symbol" src="/img/symbols/fossil.png">
          </div>
          <div class="col-md-1 centered-column">
            <?php echo "<img class='bar' src='/img/bar/bar" . $fund->measures->getMeasureScore('weapon') . ".png'>"    ?>
            <img class="round-symbol" src="/img/symbols/weapon.png">
          </div>
          <div class="col-md-3">
            <?php echo "<img class='thin-bar' src='/img/thin-bar/thinbar" . $fund->measures->getMeasureScore('alcohol') . ".png'>" ?>
            <?php echo "<img class='thin-bar' src='/img/thin-bar/thinbar" . $fund->measures->getMeasureScore('tobacco') . ".png'>"   ?>
            <?php echo "<img class='thin-bar' src='/img/thin-bar/thinbar" . $fund->measures->getMeasureScore('gambling'). ".png'>"   ?>
            <br>
            <img class="thin-symbol" src="/img/symbols/alcohol.png">
            <img class="thin-symbol" src="/img/symbols/tobacco.png">
            <img class="thin-symbol" src="/img/symbols/gambling.png">
          </div>
        </div>
      </div>

      <?php if ($i++ == 8) break; ?> <!-- Limit to 8 funds in list -->
    <?php endforeach; ?>
  </div>
  <!-- End fund category funds -->
</section>
<section class="container">
  <h2>Värdeutveckling</h2>
  <ul>
  <?php foreach ($this->fund->fundInstances as $fi): ?>
    <li><?php echo $fi->date->format('Y-m-d') . " NAV: " .  number_format($fi->netAssetValue, 0) . " SEK"; ?></li>
  <?php endforeach ?>
  </ul>
</section>
