<div class="intro-section">
  <h2 class="centered-header">Så här enkelt är det</h2>
  <div class="row">
    <div class="col-sm-6 col-md-3">
      <div class="intro-symbol-box">
        <span class="glyphicon glyphicon-eye-open glyphicon-lg"></span>
      </div>
      <h4>1. Välj vad du vill se</h4>
      <div class="intro-box">
        <p><strong>Fondkategori</strong> - Välj var fonden
          primärt investerar. Det går även att se mer än en fondkategori åt gången.
        </p>
        <p><strong>Dina fonder</strong> -
          Lägg till de fonder du har idag eller de fonder du är intresserad
          av.
        </p>
        <p><strong>Fondbolag</strong> -
          Visa endast fonder från ett specifikt fondbolag.
        </p>
        <p><strong>Snabbsök</strong> -
          Gör en snabbsökning efter en specifik fond.
        </p>
      </div>
    </div>
    <div class="col-sm-6 col-md-3">
      <div class="intro-symbol-box">
        <span class="glyphicon-lg intro-symbol-letter">?</span>
      </div>
      <h4>2. Välj hur du vill sortera</h4>
      <div class="intro-box">

        <p>Du kan välja att sortera fonderna efter hur stor del i de investerar i:</p>
        <ul class="sort-by-explainations">
          <li>
            <img class="roundintrosymbols" src="/img/symbols/fossil.png" alt="Fossil symbol">
            Fossila bränslen
          </li>
          <li>
            <img class="roundintrosymbols" src="/img/symbols/weapon.png" alt="Weapon symbol">
            Förbjudna Vapen
          </li>
          <li>
            <img class="sqintrosymbols" src="/img/symbols/alcohol.png" alt="Alcohol symbol">
            Alkohol
          </li>
          <li>
            <img class="sqintrosymbols" src="/img/symbols/tobacco.png" alt="Tobacco symbol">
            Tobak
          </li>
          <li>
            <img class="sqintrosymbols" src="/img/symbols/gambling.png" alt="Gambling symbol">
            Spel
          </li>
        </ul>
      </div>
    </div>
    <div class="col-sm-6 col-md-3">
      <div class="intro-symbol-box">
        <span class="glyphicon-lg intro-symbol-letter">!</span>
      </div>
      <h4>3. Se resultat & jämför</h4>
      <div class="intro-box">

        <p>Vid varje mått visas en mätare som har 10 nivåer. En hög nivå innebär att fonden har få investeringar i det aktuella måttet.</p>

        <div class="row bars-explained">
          <div class="col-xs-2">
            <div class="centered-column">
              <img class="introBar" src="/img/bar/bar1.png" alt="1/10 mätare.">
            </div>
          </div>
          <div class="col-xs-10">
            <p class="bar-explanation-text"><small><em>Många bolag i fonden.</em></small></p>
          </div>
        </div>
        <div class="row bars-explained">
          <div class="col-xs-2">
            <div class="centered-column">
              <img class="introBar" src="/img/bar/bar5.png" alt="10/10 mätare.">
            </div>
          </div>
          <div class="col-xs-10">
            <p class="bar-explanation-text"><small><em>Ett fåtal bolag i fonden. </em></small></p>
          </div>
        </div>
        <div class="row bars-explained">
          <div class="col-xs-2">
            <div class="centered-column">
              <img class="introBar" src="/img/bar/bar10.png" alt="10/10 mätare.">
            </div>
          </div>
          <div class="col-xs-10">
            <p class="bar-explanation-text"><small><em>Inga bolag i fonden. </em></small></p>
          </div>
        </div>
      </div>

    </div>
    <div class="col-sm-6 col-md-3">
      <div class="intro-symbol-box">

        <span class="glyphicon glyphicon-search glyphicon-lg"></span>
      </div>
      <h4>4. Fördjupa dig</h4>
      <div class="intro-box">
        <p>Genom att klicka på en fond kommer du till <em>fondens fördjupningssida</em>. Här hittar du mer information om fonden och dess investeringar i jämförelse med andra fonder.</p>
        <p>Du kan även få mer information om fondbolagen genom att gå in på dess respektive <em>fondbolagssida</em>.</p>
        <span class="better-worse better">Fonden är bättre än snittet för fondkategorin. </span>
        <br>
        <span class="better-worse better">Fonden är bättre än snittet för alla fonder. </span>
      </div>
    </div>
  </div>
</div>
