<div class="intro-section">
  <h2 class="centered-header">Så här enkelt är det</h2>
  <div class="row">
    <div class="col-sm-6 col-md-3">
      <div class="intro-symbol-box">
        <span class="glyphicon glyphicon-eye-open glyphicon-lg"></span>
      </div>
      <h4>1. Välj vad du vill se</h4>
      <div class="intro-box">
        <p><strong>Fondkategori</strong> - Välj var fonden
          primärt investerar. Det går även att se mer än en fondkategori åt gången.
        </p>
        <p><strong>Dina fonder</strong> -
          Lägg till de fonder du har idag eller de fonder du är intresserad
          av.
        </p>
        <p><strong>Fondbolag</strong> -
          Visa endast fonder från ett specifikt fondbolag.
        </p>
        <p><strong>Snabbsök</strong> -
          Gör en snabbsökning efter en specifik fond.
        </p>
      </div>
    </div>
    <div class="col-sm-6 col-md-3">
      <div class="intro-symbol-box">
        <span class="glyphicon-lg intro-symbol-letter">?</span>
      </div>
      <h4>2. Välj hur du vill ranka</h4>
      <div class="intro-box">

        <p>Du kan välja att ranka fonderna efter hur stor del i de investerar i:</p>
        <ul class="sort-by-explainations">
          <li>
            <img class="roundintrosymbols" src="/img/symbols/fossil.png" alt="Fossil symbol">
            Fossila bränslen
          </li>
          <li>
            <img class="roundintrosymbols" src="/img/symbols/weapon.png" alt="Weapon symbol">
            Förbjudna Vapen
          </li>
          <li>
            <img class="sqintrosymbols" src="/img/symbols/alcohol.png" alt="Alcohol symbol">
            Alkohol
          </li>
          <li>
            <img class="sqintrosymbols" src="/img/symbols/tobacco.png" alt="Tobacco symbol">
            Tobak
          </li>
          <li>
            <img class="sqintrosymbols" src="/img/symbols/gambling.png" alt="Gambling symbol">
            Spel
          </li>
        </ul>
      </div>
    </div>
    <div class="col-sm-6 col-md-3">
      <div class="intro-symbol-box">
        <span class="glyphicon-lg intro-symbol-letter">!</span>
      </div>
      <h4>3. Se resultat & jämför</h4>
      <div class="intro-box">

        <p>Om du valt att ranka efter exempelvis <em>fossila bränslen</em> är de fonder som visas högst upp i listan de fonder som investerar i minst antal bolag med <em>fossil bränslen</em>.</p>
        <p>För att ge en överblick visas även fondens resultat gällande de övriga mätten. Du kan när som helst välja att ranka efter ett nytt mått.</p>
        <div class="row bars-explained">
          <div class="col-md-2">
            <div class="centered-column">
              <img id="introBar" src="/img/bar/bar10.png" alt="10/10 mätare.">
            </div>

          </div>
          <div class="col-md-10">
            <p><small><em>Inga/väldigt få bolag med fossila bränslen i fonden. </em></small></p>
          </div>

        </div>
      </div>

    </div>
    <div class="col-sm-6 col-md-3">
      <div class="intro-symbol-box">

        <span class="glyphicon glyphicon-search glyphicon-lg"></span>
      </div>
      <h4>4. Fördjupa dig</h4>
      <div class="intro-box">
        <p>Genom att klicka på en fond kommer du till <em>fondens fördjupningssida</em>. Här hittar du mer information om fonden och dess investeringar i jämförelse med andra fonder.</p>
        <p>Du kan även få mer information om fondbolagen fenom att gå in på dess respektive <em>fondbolagssida</em>.</p>
        <span class="better-worse better">Fonden är bättre än snittet för fondkategorin. </span>
        <br>
        <span class="better-worse better">Fonden är bättre än snittet för alla fonder. </span>
      </div>
    </div>
  </div>
</div>
