<?php // sustainability-categories.phtml

$sform = $this->sform;
$sform->setAttribute('method', 'POST');
$sform->setAttribute('action', $this->url('change-sustainability-categories'));
$sform->prepare();
$submit = $sform->get('submit');
$submit->setValue('Välj kategorier');
?>

<div class="well sustainability-categories clearfix info-box">
  <div class="row">
  <p class="col-sm-10">
    <strong><?php echo $this->translate('Valda hållbarhetskategorier:') ?></strong>
    <?php
     $categories = $this->sustainability;
      foreach($categories as $category) {
        if ($category !== end($categories))
          echo $this->translate((string)$category) . ", ";
        if ($category === end($categories))
          echo $this->translate((string)$category) . ".";
      }
    ?>
  </p>
  <div class="col-sm-2">
    <button type="button" class="btn btn-primary pull-right btn-sus-cat-collapse" data-toggle="collapse" data-target="#sustainability-form"><?php echo $this->translate('Ändra') ?></button>
  </div>
  </div>

  <div id="sustainability-form" class="collapse">
    <div class="sus-form-collapseable-holder">
      <div class="">
        <?php echo $this->form()->openTag($sform) ?>
        <div class="checkbox">
          <?php
          $this->formMultiCheckbox()->setSeparator('</div><div class="checkbox">');
          echo $this->formMultiCheckbox($sform->get('sustainability'));
          ?>
        </div>
        <br />
        <?php echo $this->formSubmit($submit) ?>
        <?php echo $this->form()->closeTag() ?>
      </div>
      <div class="">
        <h3><?php echo $this->translate('Hållbarhetskategorier förklarade') ?></h3>
        <?php echo $this->partial('sustainability-categories-explained'); ?>
      </div>
    </div>
  </div>
</div>
