<p><?php echo $this->translate('Hållbarhetsnivån på fonder bestäms från vilka kategorier du väljer.') ?></p>
<ul>
  <li><strong><?php echo $this->translate('Förbjudna vapen') ?></strong> - <?php echo $this->translate('Företag som tillverkar vapen som anses som inhumana, där inräknas personminor och klusterbomber. Här har vi även räknat in företag som tillverkar kärnvapen. ') ?></li>
  <li><strong><?php echo $this->translate('Miljöförstöring') ?></strong> - <?php echo $this->translate('Företag anklagade och eller dömda för allvarlig miljöförstöring. ') ?></li>
  <li><strong><?php echo $this->translate('Brott mot mänskliga rättigheter') ?></strong> - <?php echo $this->translate('Företag dömda för brott mot mänskliga rättigheter och arbetsrättsliga mål.') ?> </li>
  <li><strong><?php echo $this->translate('Fossila bränslen') ?></strong> - <?php echo $this->translate('Företag som tar upp olja, kol eller gas.') ?></li>
</ul>
