<p>Hållbarhetsnivån på fonder bestäms från vilka kategorier du väljer.</p>
<ul>
  <li><strong>Förbjudna vapen</strong> - Företag som tillverkar vapen som anses som inhumana, där inräknas personminor och klusterbomber. Här har vi även räknat in företag som tillverkar kärnvapen. </li>
  <li><strong>Miljöförstöring</strong> - Företag anklagade och eller dömda för allvarlig miljöförstöring. </li>
  <li><strong>Brott mot mänskliga rättigheter</strong> - Företag dömda för brott mot mänskliga rättigheter och arbetsrättsliga mål. </li>
  <li><strong>Fossila bränslen</strong> - Företag som tar upp olja, kol eller gas.</li>
</ul>
