<p>Hållbarhetsnivån på fonder bestäms från vilka kategorier du väljer.</p>
<ul>
  <li>Förbjudna vapen - Företag som tillverkar vapen som anses som inhumana, där inräknas personminor och klusterbomber. Här har vi även räknat in företag som tillverkar kärnvapen. </li>
  <li>Miljöförstöring - Företag anklagade och eller dömda för allvarlig miljöförstöring. </li>
  <li>Brott mot mänskliga rättigheter - Företag dömda för brott mot mänskliga rättigheter och arbetsrättsliga mål. </li>
  <li>Fossila bränslen - Företag som tar upp olja, kol eller gas.</li>
</ul>
