#!/bin/bash
source ~/Sites/fondout/script/dbconfig.local
mysqldump --opt -u $DB_USER -p$DB_PASS $DB_FONDOUT > ~/Google\ Drive/Sparfabriken/Databasdumpar/$DB_FONDOUT\_$( date +%Y )_$( date +%m )_$( date +%d ).sql
