#!/bin/bash
source ~/Sites/fondout/script/dbconfig.local
mysqldump --opt -u $DB_USER -p$DB_PASS fund_search > ~/Google\ Drive/Sparfabriken/Databasdumpar/fund_search\_$( date +%Y )_$( date +%m )_$( date +%d ).sql
