#!/bin/bash
source ~/Sites/fondout/script/dbconfig.local
mysqldump --opt -u $DB_USER -p$DB_PASS fondout_test > ~/Google\ Drive/Sparfabriken/Databasdumpar/fondout_test\_$( date +%Y )_$( date +%m )_$( date +%d ).sql
