<?php
$this->headScript()
->appendFile($this->basePath() . '/js/index.js')
->prependFile($this->basePath() . '/vendor/chartjs/Chart.min.js')
->appendFile($this->basePath() . '/js/sustainability-chart.js');

$form->setAttribute('method', 'POST');
$form->setAttribute('action', $this->url('change-sustainability-categories', array(), array('query' => array('redirect' => 'funds'))));
$form->setAttribute('class', 'sustainability-categories form-inline well');
$form->prepare();
$submit = $form->get('submit');
$submit->setValue('Hitta fonder');
$submit->setAttribute('class', $submit->getAttribute('class') . ' btn-success btn-block');
//$submit->setAttribute('class', $submit->getAttribute('class') . '');
?>

<section class="featurette first-section-landing-page">
    <div class="container">

        <div class="row header-row">
          <h1><?php echo $this->translate('Dags att fondera?') ?></h1>
          <h3><?php echo $this->translate('Fondjämförelser ur ett hållbarhetsperspektiv har aldrig varit enklare.') ?></h3>
        </div>

        <div class="row">
          <div class="col-lg-10 col-lg-offset-1">
            <?php echo $this->form()->openTag($form) ?>
            <h3 id="front-sustainibility-form-label">Undvik att investera i:
              <a href="javascript://" data-toggle="popover" tabindex="0" data-placement="auto" data-trigger="focus"
              title="Hållbarhetsnivå"
              data-content="
              <p>Hållbarhetsnivån på fonder bestäms från vilka kategorier du väljer.</p>
                <ul>
                  <li><strong>Förbjudna vapen</strong> - Företag som tillverkar vapen som anses som inhumana, där inräknas personminor och klusterbomber. Här har vi även räknat in företag som tillverkar kärnvapen. </li>
                  <li><strong>Miljöförstöring</strong> - Företag som står skyldiga till allvarlig miljöförstöring. </li>
                  <li><strong>Brott mot mänskliga rättigheter</strong> - Företag skyldiga till brott mot mänskliga rättigheter och i arbetsrättsliga frågor. </li>
                  <li><strong>Fossila bränslen</strong> - Företag som tar upp olja, kol eller gas.</li>
                <ul>
                ">
                <span class="glyphicon glyphicon-info-sign"></span>
                </a>
            </h3>
            <div class="checkbox">
                <?php
                    $this->formMultiCheckbox()->setSeparator('</div><div class="checkbox">');
                    echo $this->formMultiCheckbox($form->get('sustainability'));
                ?>
            </div>

            <?php echo $this->formSubmit($submit) ?>
            <?php echo $this->form()->closeTag() ?>
        </div>
      </div>
    </div>
</section>

<section class="featurette">
  <div class="container">
    <div class="row" style="">
      <div class="col-sm-4 glyph-explainations">
        <span class=" glyphicon glyphicon-pencil"></span>
        <br>
        <h4>
          1. Hållbarhetspreferenser
        </h4>
        <p>
          Välj dina hållbarhetspreferenser genom att klicka i de aktiviteter du
          vill undvika att investera i.
        </p>
      </div>
      <div class="col-sm-4 glyph-explainations">
        <span class="glyphicon glyphicon-globe"></span>
        <br>
        <h4>
          2. Hållbarhetsnivå & CO<sub>2</sub>-utsläpp
        </h4>
        <p>
          Dina val matchas med fonderna i vår databas (>200 st) och presenteras
          utifrån hållbarhetsnivå och CO<sub>2</sub>-utsläpp.
          <a href="/products"> Läs mer om våra mått här </a>
        </p>
      </div>
      <div class="col-sm-4 glyph-explainations">
        <span class="glyphicon glyphicon-heart-empty"></span>
        <br>
        <h4>
          3. Se fonder
        </h4>
        <p>
          Fonderna som visas ligger i linje med dina hållbarhetspreferenser. Nu är valet upp till dig.
        </p>
      </div>
    </div>
  </div>
</section>


<section class="featurette callout">
    <div class="container small-container">
        <div class="row">
          <h1>Upp till dig.</h1>
          <p class="lead"><?php echo $this->translate('Som du säkert redan vet, innebär fondsparande att man äger små andelar av de företag som ingår i fonden. En del har koll på exakt vilka företag som ingår, andra inte.
          Detta må inte heller vara det mest intressanta.
          ') ?></p>
          <p class="lead"><?php echo $this->translate('Vad vi på <strong>Sparfabriken</strong> dock anser vara högintressant, utöver avkastning, är att försäkra sig om att fonden du sparar i förvaltar dina pengar i enighet med just dina förväntningar på en hållbar framtid.') ?></p>
        </div>
    </div>
</section>
<section class="featurette callout double-callout">
  <div class="container small-container">
    <div class="row">
      <h1>Sparande för framtiden.</h1>
      <p class="lead"><?php echo $this->translate('När man hör ordet “sparande” tänker nog de flesta på att lägga undan pengar för att kunna använda dessa i framtiden. Det är självfallet även önskvärt att dessa undanlagda pengar ska öka i värde. Detta håller vi fullständigt med om.
      ') ?></p>
      <p class="lead"><?php echo $this->translate('För oss innebär sparande dock mer än så. För oss innebär sparande att inte slösa på jordens resurser och att ta tillvara på sin etik och moral. För oss går sparande och hållbarhet hand i hand.') ?></p>
      <p class="lead"><?php echo $this->translate('<em><strong>- Varför spara för framtiden om man inte bryr sig om hur den ser ut?</strong></em>') ?> </p>

    </div>
  </div>
</section>

<section class="featurette">
  <div class="container small-container">
    <div class="section-chevron-down">
      <span class="glyphicon glyphicon-chevron-down"></span>
    </div>
    <div class="row">
      <h1>Våra mått</h1>
      <h2>Hållbarhetsnivå</h2>
        <!--
        <div class="dummy-chart">
          <div class="chart-container">
            <canvas class="sustainability-chart" data-percentage="0.7"></canvas>
          </div>
        </div>
        -->

      <p class="lead">Varje fond mäts av ett hållbarhetsnivå som räknas ut från de parametrar du tycker är viktiga,
      vad är en hållbar fond? Se vilka fonder som investerar hållbart och väljer bort fossila bränslen.  </p>

      <h2>Koldioxidutsläpp</h2>
      <p class="lead">Varför inte jämföra koldioxidutsläpp på dina fonder när man redan gör det på så mycket annat? Detta kanske är den plats man kan påverka mest.</p>


    </div>
  </div>
</section>
<section class="featurette callout">
  <div class="container small-container">
    <div class="section-chevron-down">
      <span class="glyphicon glyphicon-chevron-down"></span>
    </div>
    <div class="row">
      <h1>Om Sparfabriken</h1>
      <p class="lead">Sparfabriken har sin bas i Lund och jobbar med att tillgängliggöra information om sparande. Vi arbetar kontinuerligt med att ta fram bättre sätt att jämföra och analysera fonder. Det arbete vi gjort med bland andra Världsnaturfonden WWF Sverige och Swedwatch har resulterat i det som idag är sparfabriken.se. </p>
    </div>
  </div>
</section>
