<?php
$this->headScript()
->appendFile($this->basePath() . '/js/index.js');

$form->setAttribute('method', 'POST');
$form->setAttribute('action', $this->url('change-sustainability-categories', array(), array('query' => array('redirect' => 'funds'))));
$form->setAttribute('class', 'sustainability-categories form-inline well');
$form->prepare();
$submit = $form->get('submit');
$submit->setValue('Hitta fonder');
$submit->setAttribute('class', $submit->getAttribute('class') . ' btn-primary btn-block btn-lg');
//$submit->setAttribute('class', $submit->getAttribute('class') . '');
?>

<section class="featurette first-section-landing-page">
    <div class="container">

        <div class="row header-row font-smoothing">
          <h1><?php echo $this->translate('Dags att fondera?') ?></h1>
          <h3><?php echo $this->translate('Fondjämförelser ur ett hållbarhetsperspektiv har aldrig varit enklare.') ?></h3>
        </div>

        <div class="row">

            <?php echo $this->form()->openTag($form) ?>
            <h3 id="front-sustainibility-form-label">Undvik att investera i:
              <a href="javascript://" data-toggle="popover" tabindex="0" data-placement="auto" data-trigger="focus"
              title="Hållbarhetsnivå"
              data-content="
                <?php echo $this->partial('sustainability-categories-explained'); ?>
                ">
                <span class="glyphicon glyphicon-info-sign"></span>
                </a>
            </h3>
            <div class="checkbox">
                <?php
                    $this->formMultiCheckbox()->setSeparator('</div><div class="checkbox">');
                    echo $this->formMultiCheckbox($form->get('sustainability'));
                ?>
            </div>

            <?php echo $this->formSubmit($submit) ?>
            <?php echo $this->form()->closeTag() ?>

      </div>
    </div>
</section>

<section class="featurette">
  <div class="container">
    <div class="row" style="">
      <div class="col-sm-4 glyph-explainations">
        <span class=" glyphicon glyphicon-pencil"></span>
        <br>
        <h4>
          1. Hållbarhetspreferenser
        </h4>
        <p>
          Välj dina hållbarhetspreferenser genom att klicka i de aktiviteter du
          vill undvika att investera i.
        </p>
      </div>
      <div class="col-sm-4 glyph-explainations">
        <span class="glyphicon glyphicon-globe"></span>
        <br>
        <h4>
          2. Hållbarhetsnivå & CO<sub>2</sub>-utsläpp
        </h4>
        <p>
          Dina val matchas med fonderna i vår databas och presenteras
          utifrån hållbarhetsnivå och CO<sub>2</sub>-utsläpp.
          <br>
          <a href="#products"> Läs mer om våra mått här </a>
        </p>
      </div>
      <div class="col-sm-4 glyph-explainations">
        <span class="glyphicon glyphicon-heart-empty"></span>
        <br>
        <h4>
          3. Se fonder
        </h4>
        <p>
          Fonderna som visas ligger i linje med dina hållbarhetspreferenser. Nu är valet upp till dig.
        </p>
      </div>
    </div>
  </div>
</section>


<section class="featurette callout">
    <div class="container">
        <div class="row">
          <h1>Upp till dig.</h1>
          <p class="lead"><?php echo $this->translate('Som du säkert redan vet, innebär fondsparande att man äger små andelar av de företag som ingår i fonden. En del har koll på exakt vilka företag som ingår, andra inte.
          Detta må inte heller vara det mest intressanta.
          ') ?></p>
          <p class="lead"><?php echo $this->translate('Vad vi på <strong>Sparfabriken</strong> dock anser vara högintressant, utöver avkastning, är att försäkra sig om att fonden du sparar i förvaltar dina pengar i enighet med just dina förväntningar på en hållbar framtid.') ?></p>
        </div>
    </div>
</section>
<section class="featurette callout double-callout">
  <div class="container">
    <div class="row">
      <h1>Sparande för framtiden.</h1>
      <p class="lead"><?php echo $this->translate('När man hör ordet “sparande” tänker nog de flesta på att lägga undan pengar för att kunna använda dessa i framtiden. Det är självfallet även önskvärt att dessa undanlagda pengar ska öka i värde. Detta håller vi fullständigt med om.
      ') ?></p>
      <p class="lead"><?php echo $this->translate('För oss innebär sparande dock mer än så. För oss innebär sparande att inte slösa på jordens resurser och att ta tillvara på sin etik och moral. För oss går sparande och hållbarhet hand i hand.') ?></p>
      <p class="lead"><?php echo $this->translate('<em><strong>- Varför spara för framtiden om man inte bryr sig om hur den ser ut?</strong></em>') ?> </p>

    </div>
  </div>
</section>

<section id="products" class="featurette">
  <div class="container">
    <div class="section-chevron-down">
      <span class="glyphicon glyphicon-chevron-down"></span>
    </div>
    <div class="row">
  <!--    <h1>Våra mått</h1>
      <h2>Hållbarhetsnivå</h2>
    -->
        <!--
        <div class="dummy-chart">
          <div class="chart-container">
            <canvas class="sustainability-chart" data-percentage="0.7"></canvas>
          </div>
        </div>
        -->
<!--
      <p class="lead">Varje fond mäts av ett hållbarhetsnivå som räknas ut från de parametrar du tycker är viktiga,
      vad är en hållbar fond? Se vilka fonder som investerar hållbart och väljer bort fossila bränslen.  </p>

      <h2>Koldioxidutsläpp</h2>
      <p class="lead">Varför inte jämföra koldioxidutsläpp på dina fonder när man redan gör det på så mycket annat? Detta kanske är den plats man kan påverka mest.</p>
-->


<h1>Våra mått</h1>
<div class="row header-with-symbol">
  <div class="header-symbol">
    <img src="img/sustainability-score-symbol.png" alt="Hållbarhetsnivå-symbol" />
  </div>
  <h2>Hållbarhetsnivå</h2>
</div>
<p>Sparfabrikens fond-hållbarhetsnivå utgår ifrån till vilken grad fonden investerat i kontroversiella bolag och redovisas på en tiogradig skala. Den 10-gradiga skalan är inte en direkt översättning av hur stor del hållbara bolag fonden har utan ett betyg som viktat från en normalfördelning för att enkelt kunna se skillnad på fonder (så att inte alla fonder får 10/10).

  De bolag vi valt ut som ohållbara kommer från andra fonders uteslutningar och är sorterade under fyra kategorier: Förbjudna vapen, Miljöförstöring, Brott mot mänskliga rättigheter och  Fossila bränslen.</p>

  <h3>Exempel på hållbarhetsnivå</h3>
  <p>
    Swedbank Robur Ethica Sverige - har bara hållbara bolag - betyg 10/10
    <br>
    Länsförsäkringar Sverige Index -  har en investering i fossila bränslen nämligen Lundin Petroleum - betyg 9/10
    <br>
    Länsförsäkringar Europa Index - har många bolag som inte är hållbara.
    <strong>Kärnvapentillverkare</strong>: Babcock international group, Thales och Rolls-Royce.
    Företag som dömts för <strong>allvarlig miljöförstöring</strong>: Shell, BP, Rio Tinto
    Företag dömda för brott mot <strong>mänskliga rättigheter</strong>: Deutsche Telecom, Eutelsat, Communications, Heidelberg Cement.
    Företag som tar upp och säljer <strong>fossila bränslen</strong>: BHP Billiton, BP, Total S.A., Royal Dutch Shell, ENI S.p.A., Repsol YPF S.A., BG Group PLC, Statoil, OMV AG, Tullow Oil PLC, GDF Suez S.A., Anglo American PLC, Rio Tinto Co. Ltd., RWE AG, ArcelorMittal, Lundin Petroleum.
    <br>
    Sammanfattningsvis en stor andel ohållbara bolag - fonden får därför betyg 6/10 då många bolagen i fonden ändå är hållbara, över 400 stycken.
  </p>
  <div class="row header-with-symbol">
    <div class="header-symbol">
      <img src="img/co2-symbol.png" alt="Koldioxitutsläpp-symbol" />
    </div>
    <h2>Koldioxidutsläpp </h2>
  </div>

  <p>
    Företag mäter i CO<sub>2</sub>-utsläpp i en standard från Greenhouse gas protocol (GHG) som delats upp i tre delar: scope 1, 2, och 3.
    Förenklat kan man säga att:
  </p>
  <ul>
    <li>Scope 1 är direkta utsläpp som företaget ger upphov till genom exempelvis förbränning. </li>
    <li>Scope 2 är indirekta utsläpp som köpt energi i form av elektricitet eller ånga.</li>
    <li>Scope 3 är övriga indirekta utsläpp från tex. energi som underkonsulter använder tex om man köper en budtjänst.</li>
  </ul>
  <p>
    <a href="http://coolclimate.berkeley.edu/node/405" target="_blank">
      Läs en bra förklaring på scope 1, 2, 3
    </a>
    <br>
    <a href="http://www.ghgprotocol.org/" target="_blank">
    Läs mer om GHG
    </a>
  </p>

  <p>I våra beräkningar väljer vi att ta med de utsläpp som är närmast företaget i sig genom att använda scope 1 och scope 2. Detta är siffror som de flesta börsnoterade företag själva tar fram och redovisar årligen, det finns stora ramverk för hur man kan revidera om mätningarna är korrekta bland annat Global Reporting Initiative(GRI) som gör det till en prestige för företag att nå upp till deras krav. GRIs kravnivåer har fler parametrar än bara CO<sub>2</sub>-utsläpp.</p>


    </div>
    <div class="row">
      <a href="<?php echo $this->url('funds') ?>" class="btn btn-primary btn-block">Gå till Fondsök</a>
    </div>
  </div>
</section>
<section id="contact" class="featurette callout">
  <div class="container">
    <div class="section-chevron-down">
      <span class="glyphicon glyphicon-chevron-down"></span>
    </div>
    <div class="row">
      <h1>Om Sparfabriken</h1>
      <p class="lead">
        Sparfabriken har sin bas i Lund och jobbar med att tillgängliggöra information om sparande.
        Vi arbetar kontinuerligt med att ta fram bättre sätt att jämföra och analysera fonder.
        Det arbete vi gjort med bland andra Världsnaturfonden WWF Sverige och
        Swedwatch har resulterat i det som idag är sparfabriken.se.
      </p>

    </div>
    <div class="row">

      <address class="vcard col-md-2">
        <strong><span class="fn">Stefan Carlsson</span></strong><br />
        <span class="role">Sparekonom</span><br />
        <a class="email" href="mailto:&#115;&#116;&#101;&#102;&#097;&#110;&#064;&#115;&#112;&#097;&#114;&#102;&#097;&#098;&#114;&#105;&#107;&#101;&#110;&#046;&#115;&#101;">&#115;&#116;&#101;&#102;&#097;&#110;&#064;&#115;&#112;&#097;&#114;&#102;&#097;&#098;&#114;&#105;&#107;&#101;&#110;&#046;&#115;&#101;</a><br />
        <span class="tel">+46 70 - 227 12 50</span>
      </address>

      <div class="col-md-3">
        <div class="thumbnail">
          <img src='/img/people/stefan.png' alt="Stefan Carlsson">
          <div class="caption image-text">
            <h4>Stefan Carlsson</h4>
          </div>
        </div>
      </div>
      <address class="vcard col-md-2">
        <strong><span class="fn">Petter Söderlund</span></strong><br />
        <span class="role">Teknik</span><br />
        <a class="email" href="mailto:&#112;&#101;&#116;&#116;&#101;&#114;&#064;&#115;&#112;&#097;&#114;&#102;&#097;&#098;&#114;&#105;&#107;&#101;&#110;&#046;&#115;&#101;">&#112;&#101;&#116;&#116;&#101;&#114;&#064;&#115;&#112;&#097;&#114;&#102;&#097;&#098;&#114;&#105;&#107;&#101;&#110;&#046;&#115;&#101;</a><br />
      </address>


      <div class="col-md-3">
        <div class="thumbnail">
          <img src='/img/people/petter.png' alt="Petter Söderlund">
          <div class="caption image-text">
            <h4>Petter Söderlund</h4>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>
