<?php
$this->headScript()
->appendFile($this->basePath() . '/js/index.js');

$form->setAttribute('method', 'POST');
$form->setAttribute('action', $this->url('change-sustainability-categories', array(), array('query' => array('redirect' => 'funds'))));
$form->setAttribute('class', 'sustainability-categories form-inline well');
$form->prepare();
$submit = $form->get('submit');
$submit->setValue('Hitta fonder');
$submit->setAttribute('class', $submit->getAttribute('class') . ' btn-primary btn-block btn-lg');
?>

<section class="featurette first-section-landing-page">
    <div class="container">

        <div class="row header-row font-smoothing">
          <h1><?php echo $this->translate('Dags att fondera?') ?></h1>
          <h3><?php echo $this->translate('Fondjämförelser ur ett hållbarhetsperspektiv har aldrig varit enklare.') ?></h3>
        </div>

        <div class="row">

            <?php echo $this->form()->openTag($form) ?>
            <h3 id="front-sustainibility-form-label">Undvik att investera i:
              <a href="javascript://" data-toggle="popover" tabindex="0" data-placement="auto" data-trigger="focus"
              title="Hållbarhetsnivå"
              data-content="
                <?php echo $this->partial('sustainability-categories-explained'); ?>
                ">
                <span class="glyphicon glyphicon-info-sign"></span>
                </a>
            </h3>
            <div class="checkbox">
                <?php
                    $this->formMultiCheckbox()->setSeparator('</div><div class="checkbox">');
                    echo $this->formMultiCheckbox($form->get('sustainability'));
                ?>
            </div>

            <?php echo $this->formSubmit($submit) ?>
            <?php echo $this->form()->closeTag() ?>

      </div>
    </div>
</section>

<section class="featurette">
  <div class="container">
    <div class="row" style="">
      <div class="col-sm-4 glyph-explainations">
        <span class=" glyphicon glyphicon-pencil"></span>
        <br>
        <h4>
          1. Hållbarhetspreferenser
        </h4>
        <p>
          Välj dina hållbarhetspreferenser genom att klicka i de aktiviteter du
          vill undvika att investera i.
        </p>
      </div>
      <div class="col-sm-4 glyph-explainations">
        <span class="glyphicon glyphicon-globe"></span>
        <br>
        <h4>
          2. Hållbarhetsnivå & CO<sub>2</sub>-utsläpp
        </h4>
        <p>
          Dina val matchas med fonderna i vår databas och rankas efter hållbarhetsnivå. Du kan även välja att ranka fonderna utifrån CO<sub>2</sub>-utsläpp.
        </p>
      </div>
      <div class="col-sm-4 glyph-explainations">
        <span class="glyphicon glyphicon-heart-empty"></span>
        <br>
        <h4>
          3. Se fonder
        </h4>
        <p>
          Fonderna som visas överst ligger i linje med dina hållbarhetspreferenser. Valet är upp till dig.
        </p>
      </div>
    </div>
  </div>
</section>


<section class="featurette callout">
    <div class="container">
        <div class="row">
          <h1>Vet du vad?</h1>
          <p class="lead"><?php echo $this->translate('
          Sannolikheten att du har pengar i fonder är väldigt hög – cirka 90 % av Sveriges befolkning har det i någon form. Även om du inte är en aktiv fondsparare så äger du fonder exempelvis genom ditt pensionssparande.
          ') ?></p>
          <p class="lead"><?php echo $this->translate('
          Som du kanske redan vet, innebär fondsparande att du indirekt äger andelar i de bolag som ingår i fonden. Men vet du vad du sparar i? Vilka bolag du äger? Vad de pysslar med? Vet du om dina pengar förvaltas i linje med dina förväntningar på en hållbar framtid? Om inte är det dags att börja <em>fondera</em>.
          ') ?></p>
          <p class="lead finish-words">
            <?php echo $this->translate('Sparfabriken låter dig veta vad. Hållbarhetspreferenser och fondval är helt upp till dig. ') ?>
           </p>

        </div>
    </div>
</section>

<section id="sea-info-text-section" class="featurette">
  <div class="container">
    <div class="row">
      <div class="col-sm-5 col-sm-offset-7 col-md-4 col-md-offset-8 well" style="background-color: rgba(199,200,200,0.75);">
        <h3>Hållbarhet eller avkastning?</h3>
        <p>
          Oavsett vad folk säger så är sanningen –dessvärre- att ingen på förhand kan veta hur börsen kommer att gå. Det finns ingen garanti att en fond som tidigare har gått bra kommer att gå lika bra i framtiden. Det finns inte heller något som visar att en hållbar fond inte kan uppvisa lika hög (eller högre!) avkastning som en mindre hållbar fond. Du behöver alltså inte välja det ena eller det andra. Eller rättare sagt, du kan bara välja det ena. Det andra vet du först i efterhand.
        </p>
      <div>
    </div>
  </div>
</section>

<section id="products" class="featurette">
  <div class="container">
    <div class="section-chevron-down">
      <span class="glyphicon glyphicon-chevron-down"></span>
    </div>
    <div id="index-measurements" class="row">

      <h1>Hållbarhetsnivå</h1>
      <div id="index-sustainability-measure" class ="row">
        <div class="col-sm-4">
          <h3>Förbjudna vapen</h3>
          <p>
              Innehåller din fond vapen som anses vara inhumana?
          </p>
          <h3>Miljöförstöring</h3>
          <p>
            Innehåller din fond företag som är anklagade och dömda för miljöförstöring?
          </p>
        </div>

        <div class="col-sm-4">
              <img src="img/sustainability-score-symbol-lg.gif" alt="Hållbarhetsnivå-symbol" style="width: 80%" />
        </div>
        
        <div class="col-sm-4">
          <h3>Brott mot mänskliga rättigheter</h3>
          <p>
            Innehåller din fond företag dömda för brott mot mänskliga rättigheter och arbetsrättsliga mål?
          </p>
          <h3>Fossila bränslen</h3>
          <p>
            Innehåller din fond företag som äger och tar upp olja, kol och gas?
          </p>
        </div>

      </div>

      <div id="index-co2-measure" class="row">
        <img src="img/co2-symbol.png" alt="Koldioxitutsläpp-symbol" style="zoom:1.5" />
        <h3>Koldioxidutsläpp</h3>
        <p>Ett mått på fondens koldioxidutsläpp.</p>
      </div>
    </div>
    <div class="row">
      <a href="<?php echo $this->url('funds') ?>" class="btn btn-primary btn-block">Gå till Fondsök</a>
    </div>
  </div>
</section>


<section id="contact" class="featurette callout">
  <div class="container">
    <div class="section-chevron-down">
      <span class="glyphicon glyphicon-chevron-down"></span>
    </div>
    <div class="row">
      <h1>Om oss</h1>

      <p class="lead">
        Sparfabriken har sin bas i Lund och jobbar med att tillgängliggöra hållbart sparande. Vi arbetar kontinuerligt med att ta fram nya sätt att jämföra och analysera fonder utifrån ett hållbarhetsperspektiv – allt för att du som sparare ska kunna göra ett så bra och medvetet val som möjligt.
      </p>
      <p class="lead">
        <strong>För företag och organisationer</strong> tar vi även fram rapporter om hållbart sparande.  Kontakta oss <a class="email" href="mailto:&#115;&#116;&#101;&#102;&#097;&#110;&#064;&#115;&#112;&#097;&#114;&#102;&#097;&#098;&#114;&#105;&#107;&#101;&#110;&#046;&#115;&#101;">här</a> för mer information.
      </p>

      <ul>
        <li>WWF (gärna LOGO!) : LÄNK: ” Har du reserverat?”</li>
        <li>FOSSIL FREE LÄNK: ” Guldet till sand?”</li>
        <li>SWEDWATCH LÄNK ” Stockholms fonder</li>
      </ul>
      <br>
    </div>
    <div class="row">

      <div class="col-md-3">
        <div class="thumbnail">
          <img src='/img/people/stefan.png' alt="Stefan Carlsson">
          <div class="caption image-text">
            <h4>Stefan Carlsson</h4>
          </div>
        </div>
      </div>

      <address class="vcard col-md-3">
        <strong><span class="fn">Stefan Carlsson</span></strong><br />
        <span class="role">VD/Sparekonom</span><br />
        <a class="email" href="mailto:&#115;&#116;&#101;&#102;&#097;&#110;&#064;&#115;&#112;&#097;&#114;&#102;&#097;&#098;&#114;&#105;&#107;&#101;&#110;&#046;&#115;&#101;">&#115;&#116;&#101;&#102;&#097;&#110;&#064;&#115;&#112;&#097;&#114;&#102;&#097;&#098;&#114;&#105;&#107;&#101;&#110;&#046;&#115;&#101;</a><br />
        <span class="tel">+46 70 - 227 12 50</span>
      </address>

      <div class="col-md-3">
        <div class="thumbnail">
          <img src='/img/people/petter.png' alt="Petter Söderlund">
          <div class="caption image-text">
            <h4>Petter Söderlund</h4>
          </div>
        </div>
      </div>

      <address class="vcard col-md-3">
        <strong><span class="fn">Petter Söderlund</span></strong><br />
        <span class="role">Analytiker</span><br />
        <a class="email" href="mailto:&#112;&#101;&#116;&#116;&#101;&#114;&#064;&#115;&#112;&#097;&#114;&#102;&#097;&#098;&#114;&#105;&#107;&#101;&#110;&#046;&#115;&#101;">&#112;&#101;&#116;&#116;&#101;&#114;&#064;&#115;&#112;&#097;&#114;&#102;&#097;&#098;&#114;&#105;&#107;&#101;&#110;&#046;&#115;&#101;</a><br />
        <span class="tel">+46 70 - 379 03 62</span>
      </address>

    </div>
  </div>
</section>
