<section class="container">
  <h1>Våra mått</h1>
  <h2>Hållbarhetsnivå</h2>
  <p>Sparfabrikens fond-hållbarhetsnivå utgår ifrån till vilken grad fonden investerat i kontroversiella bolag och redovisas på en tiogradig skala. Den 10-gradiga skalan är inte en direkt översättning av hur stor del hållbara bolag fonden har utan ett betyg som viktat från en normalfördelning för att enkelt kunna se skillnad på fonder (så att inte alla fonder får 10/10).

  De bolag vi valt ut som ohållbara kommer från andra fonders uteslutningar och är sorterade under fyra kategorier: Förbjudna vapen, Miljöförstöring, Brott mot mänskliga rättigheter och  Fossila bränslen.</p>

  <h3>Exempel på hållbarhetsnivå</h3>
  <p>
  Swedbank Robur Ethica Sverige - har bara hållbara bolag - betyg 10/10
  Länsförsäkringar Sverige Index -  har en investering i fossila bränslen nämligen Lundin Petroleum - betyg 9/10
  Länsförsäkringar Europa Index - har många bolag som inte är hållbara.
  <strong>Kärnvapentillverkare</strong>: Babcock international group, Thales och Rolls-Royce.
  Företag som dömts för <strong>allvarlig miljöförstöring</strong>: Shell, BP, Rio Tinto
  Företag dömda för brott mot <strong>mänskliga rättigheter</strong>: Deutsche Telecom, Eutelsat, Communications, Heidelberg Cement
  Företag som tar upp och säljer <strong>fossila bränslen</strong>: BHP Billiton, BP, Total S.A., Royal Dutch Shell, ENI S.p.A., Repsol YPF S.A., BG Group PLC, Statoil, OMV AG, Tullow Oil PLC, GDF Suez S.A., Anglo American PLC, Rio Tinto Co. Ltd., RWE AG, ArcelorMittal, Lundin Petroleum
  Sammanfattningsvis en stor andel ohållbara bolag - fonden får därför betyg 6/10 då många bolagen i fonden ändå är hållbara, över 400 stycken.
  </p>
  <h2>CO2-utsläpp </h2>
  <p>
  Företag mäter i CO2-utsläpp i en standard från Greenhouse gas protocol (GHG) som delats upp i tre delar: scope 1, 2, och 3.
  Förenklat kan man säga att:
</p>
  <ul>
    <li>Scope 1 är direkta utsläpp som företaget ger upphov till genom exempelvis förbränning. </li>
    <li>Scope 2 är indirekta utsläpp som köpt energi i form av elektricitet eller ånga.</li>
    <li>Scope 3 är övriga indirekta utsläpp från tex. energi som underkonsulter använder tex om man köper en budtjänst.</li>
  </ul>
  <p>
  Läs en bra förklaring på scope 1, 2, 3 på http://coolclimate.berkeley.edu/node/405
  <br>
  Läs mer om GHG på http://www.ghgprotocol.org/.
  </p>

  <p>I våra beräkningar väljer vi att ta med de utsläpp som är närmast företaget i sig genom att använda scope 1 och scope 2. Detta är siffror som de flesta börsnoterade företag själva tar fram och redovisar årligen, det finns stora ramverk för hur man kan revidera om mätningarna är korrekta bland annat Global Reporting Initiative(GRI) som gör det till en prestige för företag att nå upp till deras krav. GRIs kravnivåer har fler parametrar än bara CO2-utsläpp.</p>
</section>
