<?php
translate('Förbjudna vapen');
translate('Miljöförstöring');
translate('Fossila bränslen');
translate('Brott mot mänskliga rättigheter');
translate('Hitta fonder');
translate('Uppdatera fondsökning');
translate('Välj fondbolag...');
translate('Välj kategorier');

/* Fondkategorier */
translate('Asien');
translate('Blandfond');
translate('Branchfond');
translate('Europa');
translate('Generationsfond');
translate('Global');
translate('Norden');
translate('Östeuropa');
translate('Sverige');
translate('Sverige & Global');
translate('Sverige småbolag');
translate('Tillväxtmarknader');
translate('USA');
